import { CommonModule } from '@angular/common';
import { Component,OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Modal,PageHeader } from '../../shared/ui';
import { SecurityService } from './security.service';
@Component({standalone:true,imports:[CommonModule,FormsModule,Modal,PageHeader],styleUrl:'./security.page.css',template:`<qai-page-header title="Security & Compliance" subtitle="API access, retention, SSO readiness and tenant security controls."><button class="button-primary" (click)="keyOpen=true">+ API key</button></qai-page-header>
<main class="page">
<div class="metric-grid"><article class="metric"><span class="icon">⌁</span><div><small>API keys</small><strong>{{ activeKeyCount }}</strong><em>Active access credentials</em></div></article><article class="metric"><span class="icon">◈</span><div><small>SSO</small><strong>{{ enabledSsoCount }}</strong><em>Configured identity providers</em></div></article><article class="metric"><span class="icon">✓</span><div><small>MFA</small><strong>{{ mfaEnabled ? 'Enabled' : 'Ready' }}</strong><em>Authenticator protection</em></div></article><article class="metric"><span class="icon">◷</span><div><small>Retention policies</small><strong>{{ retention.length }}</strong><em>Lifecycle rules configured</em></div></article></div>
<div class="content-grid"><section class="card"><header class="card-header"><div><span class="eyebrow">ACCESS CONTROL</span><h3>API keys</h3><p>Manage credentials used by trusted integrations.</p></div><span class="status">{{ activeKeyCount }} active</span></header><div class="list"><div class="list-item" *ngFor="let k of keys"><div class="stack"><b>{{k.name}}</b><span class="meta">{{k.createdAtUtc|date:'mediumDate'}} · {{k.revoked?'Revoked':'Active'}}</span></div><button class="button-quiet" *ngIf="!k.revoked" (click)="revoke(k)">Revoke</button></div></div></section>
<section class="card"><header class="card-header"><div><span class="eyebrow">IDENTITY</span><h3>SSO</h3><p>Review enterprise identity provider configuration.</p></div><span class="status">{{ enabledSsoCount }} enabled</span></header><div class="list"><div class="list-item" *ngFor="let s of sso"><div class="stack"><b>{{s.providerType|uppercase}}</b><span class="meta">{{s.entityId||'Not configured'}}</span></div><span class="status">{{s.enabled?'Enabled':'Disabled'}}</span></div></div><div class="empty" *ngIf="!sso.length">No SSO configuration yet.</div></section>
<section class="card"><header class="card-header"><div><span class="eyebrow">DATA GOVERNANCE</span><h3>Data retention</h3><p>Control automatic lifecycle rules by entity type.</p></div></header><div class="list"><div class="list-item" *ngFor="let r of retention"><div class="stack"><b>{{r.entityType}}</b><span class="meta">Automatic data lifecycle</span></div><span class="status">{{r.retentionDays}} days</span></div></div></section>
<section class="card"><header class="card-header"><div><span class="eyebrow">ACCOUNT PROTECTION</span><h3>Authenticator MFA</h3><p>Protect administrator access with a TOTP authenticator.</p></div><span class="status">{{ mfaEnabled ? 'Enabled' : 'Not enabled' }}</span></header><div class="card-body form"><p *ngIf="!mfaSecret">Protect your account with a TOTP authenticator.</p><button class="button-secondary" *ngIf="!mfaSecret" (click)="setupMfa()">Set up MFA</button><div *ngIf="mfaSecret" class="stack"><p><b>Shared key</b></p><code>{{mfaSecret}}</code><label>Authenticator code<input [(ngModel)]="mfaCode"></label><button class="button-primary" (click)="confirmMfa()">Enable MFA</button></div><button class="button-quiet" *ngIf="mfaEnabled" (click)="disableMfa()">Disable MFA</button></div></section>
<section class="card"><header class="card-header"><div><span class="eyebrow">CONTROL PLANE</span><h3>Security controls</h3><p>Baseline protections currently enforced by the platform.</p></div></header><div class="list"><div class="list-item">✓ Tenant data isolation</div><div class="list-item">✓ OpenIddict access + refresh tokens</div><div class="list-item">✓ MFA / lockout</div><div class="list-item">✓ Audit logging</div><div class="list-item">✓ Hashed API keys</div></div></section></div>
</main><qai-modal [open]="keyOpen" title="Create API key" (close)="keyOpen=false"><form class="form" (ngSubmit)="createKey()"><label>Name<input [(ngModel)]="keyName" name="name" required></label><footer class="actions"><button class="button-secondary" type="button" (click)="keyOpen=false">Cancel</button><button class="button-primary" type="submit">Create key</button></footer></form><div class="notice" *ngIf="newKey"><b>Copy this key now</b><p><code>{{newKey}}</code></p><small>It will not be returned again by the API.</small></div></qai-modal>`})
export class SecurityPage implements OnInit{keys:any[]=[];retention:any[]=[];sso:any[]=[];keyOpen=false;keyName='Server integration';newKey='';mfaSecret='';mfaCode='';mfaEnabled=false;constructor(private data:SecurityService){}get activeKeyCount(){return this.keys.filter(x=>!x.revoked).length}get enabledSsoCount(){return this.sso.filter(x=>x.enabled).length}ngOnInit(){this.load()}load(){this.data.apiKeys().subscribe(r=>this.keys=r);this.data.retention().subscribe(r=>this.retention=r);this.data.sso().subscribe(r=>this.sso=r)}createKey(){this.data.createApiKey({name:this.keyName,expiresAtUtc:null}).subscribe(r=>{this.newKey=r.key;this.keys.unshift(r)})}revoke(k:any){this.data.revokeApiKey(k.id).subscribe(()=>k.revoked=true)}setupMfa(){this.data.mfaSetup().subscribe(r=>this.mfaSecret=r.sharedKey)}confirmMfa(){this.data.mfaConfirm(this.mfaCode).subscribe(()=>{this.mfaEnabled=true;this.mfaSecret='';this.mfaCode=''})}disableMfa(){this.data.mfaDisable().subscribe(()=>this.mfaEnabled=false)}}
