import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ApiService } from '../../core/api.service';
import { PageHeader } from '../../shared/ui';

interface Tab { key: string; label: string; endpoint: string; create?: string; status?: string[]; }
interface MetricCard { label: string; value: number; tone: string; icon: string; note: string; }

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, PageHeader],
  template: `
    <qai-page-header [title]="title" [subtitle]="subtitle">
      <a routerLink="/enterprise" class="quiet-action">← Enterprise Operations</a>
      <button type="button" class="quiet-action" (click)="load()">↻ Refresh</button>
      <button type="button" class="primary-action" *ngIf="canCreate" (click)="openCreate()">＋ New {{ title }}</button>
    </qai-page-header>
    <div class="breadcrumb"><a routerLink="/enterprise">Renova</a><span>›</span><span>Enterprise Operations</span><span>›</span><strong>{{ title }}</strong></div>
    <nav class="tabs" aria-label="Enterprise modules">
      <a *ngFor="let t of tabs" [routerLink]="'/enterprise/'+t.key" [class.active]="section===t.key"><span class="tab-icon">{{ tabIcon(t.key) }}</span><span>{{t.label}}</span></a>
    </nav>
    <section class="metric-grid"><article class="metric-card" *ngFor="let card of summaryCards" [class]="'metric-card '+card.tone"><div class="metric-top"><span class="metric-icon">{{ card.icon }}</span><span class="metric-label">{{ card.label }}</span></div><strong>{{ card.value | number }}</strong><small>{{ card.note }}</small><span class="metric-spark"></span></article></section>
    <section class="list-card">
      <header class="list-header"><div><span class="eyebrow">ENTERPRISE OPERATIONS</span><h2>List of {{ title }}</h2><p>{{ rows.length | number }} records in the current Renova workspace.</p></div><div class="header-actions"><button type="button" class="export-action" (click)="exportCsv()">⇩ Export <span>⌄</span></button><button type="button" class="quiet-action" (click)="load()">↻ Refresh</button><button type="button" class="primary-action" *ngIf="canCreate" (click)="openCreate()">＋ New</button></div></header>
      <div class="filters">
        <label class="search-box"><span>⌕</span><input [(ngModel)]="search" placeholder="Search number, client or product..." /></label>
        <label class="select-box"><span>Status</span><select [(ngModel)]="statusFilter"><option value="">All statuses</option><option *ngFor="let s of statusValues" [value]="s">{{s}}</option></select></label>
        <label class="select-box"><span>Client</span><select [(ngModel)]="clientFilter"><option value="">All clients</option><option *ngFor="let c of clientValues" [value]="c">{{c}}</option></select></label>
        <label class="date-box"><span>▣</span><input type="date" [(ngModel)]="dateFrom" title="From date" /><span>–</span><input type="date" [(ngModel)]="dateTo" title="To date" /></label>
        <button type="button" class="filter-button" (click)="clearFilters()">≡ Filters <span *ngIf="hasFilters">•</span></button>
      </div>
      <div class="alert alert-error" *ngIf="error"><strong>Live workspace warning</strong><span>{{error}}</span></div>
      <div class="table-wrap" *ngIf="!loading && !error && pagedRows.length">
        <table><thead><tr><th class="check-col"><input type="checkbox" [checked]="allPageSelected" (change)="togglePage($event)" /></th><th *ngFor="let c of columns">{{c}}</th><th *ngIf="hasStatus">Workflow</th><th class="actions-col">Actions</th></tr></thead>
          <tbody><tr *ngFor="let row of pagedRows; trackBy: trackRow"><td class="check-col"><input type="checkbox" [checked]="isSelected(row)" (change)="toggleRow(row)" /></td><td *ngFor="let k of keys" [class.primary-cell]="k==='number'||k==='code'"><ng-container *ngIf="k==='status'; else normalValue"><span class="status-chip" [ngClass]="statusTone(row[k])">{{ display(row,k) }}</span></ng-container><ng-template #normalValue><span [title]="display(row,k)">{{ display(row,k) }}</span></ng-template></td><td *ngIf="hasStatus"><button type="button" class="table-link" (click)="openStatus(row)">Update status</button></td><td class="row-actions"><button type="button" class="dots" (click)="openRowActions(row)" [attr.aria-label]="'Actions for '+display(row,keys[0]||'id')">•••</button></td></tr></tbody>
        </table>
      </div>
      <div class="state" *ngIf="loading"><span class="spinner"></span><strong>Loading Renova data…</strong><span>Synchronizing this module with the Enterprise API.</span></div>
      <div class="state" *ngIf="!loading && !error && !filteredRows.length"><span class="state-icon">⌕</span><strong>{{ rows.length ? 'No matching records' : 'No Renova records yet' }}</strong><span>{{ rows.length ? 'Try another search or clear the filters.' : 'This tenant API returned no records for this module.' }}</span></div>
      <footer class="table-footer" *ngIf="!loading && !error && filteredRows.length"><span>Showing {{ pageStart + 1 }} – {{ pageEnd }} of {{ filteredRows.length | number }} {{ title.toLowerCase() }}</span><div class="pagination"><button type="button" (click)="previousPage()" [disabled]="page===1">‹</button><button type="button" *ngFor="let p of pageNumbers" [class.page-active]="p===page" (click)="goPage(p)">{{p}}</button><button type="button" (click)="nextPage()" [disabled]="page===pageCount">›</button></div></footer>
    </section>
    <section class="context-card" *ngIf="section==='warehousing'||section==='distribution'"><span class="context-icon">▣</span><div><span class="eyebrow">OPERATIONS CONTEXT</span><strong>{{ section==='warehousing' ? 'Warehouse operations' : 'Distribution operations' }}</strong><p>Facilities are filtered by type. Warehouse and distribution records remain part of the same tenant facility model.</p></div></section>

    <div class="overlay" *ngIf="modal"><section class="drawer"><header><div><small>RENOVA / ENTERPRISE</small><h2>{{modalTitle}}</h2></div><button type="button" class="close" (click)="close()">×</button></header>
      <div class="form" *ngIf="formType==='facility'"><label>Code<input [(ngModel)]="form.code"></label><label>Name<input [(ngModel)]="form.name"></label><label>Type<select [(ngModel)]="form.type"><option>Factory</option><option>Warehouse</option><option>DistributionPoint</option><option>Office</option><option>Other</option></select></label><label>Country<input [(ngModel)]="form.countryCode"></label><label>City<input [(ngModel)]="form.city"></label><label>Address<input [(ngModel)]="form.address"></label><label>Latitude<input type="number" [(ngModel)]="form.latitude"></label><label>Longitude<input type="number" [(ngModel)]="form.longitude"></label><label>Contact<input [(ngModel)]="form.contactName"></label><label>Phone<input [(ngModel)]="form.contactPhone"></label><label>Email<input [(ngModel)]="form.contactEmail"></label><label>Capacity<input type="number" [(ngModel)]="form.capacity"></label><label>Capacity unit<input [(ngModel)]="form.capacityUnit"></label><label class="check"><input type="checkbox" [(ngModel)]="form.isActive"> Active</label></div>
      <div class="form" *ngIf="formType==='customer'"><label>Company ID<input [(ngModel)]="form.companyId" placeholder="GUID"></label><label>Credit limit<input type="number" [(ngModel)]="form.creditLimit"></label><label>Payment terms days<input type="number" [(ngModel)]="form.paymentTermsDays"></label></div>
      <div class="form" *ngIf="formType==='priceList'"><label>Code<input [(ngModel)]="form.code"></label><label>Name<input [(ngModel)]="form.name"></label><label>Currency<input [(ngModel)]="form.currency"></label><label class="check"><input type="checkbox" [(ngModel)]="form.isActive"> Active</label></div>
      <div class="form" *ngIf="formType==='order'"><label>Channel<select [(ngModel)]="form.channel"><option>B2C</option><option>B2B</option><option>Distributor</option><option>Partner</option></select></label><label>Currency<input [(ngModel)]="form.currency"></label><label>Company ID<input [(ngModel)]="form.companyId"></label><label>Customer account ID<input [(ngModel)]="form.customerAccountId"></label><label>Contact ID<input [(ngModel)]="form.contactId"></label><label>Requested delivery<input type="datetime-local" [(ngModel)]="form.requestedDeliveryAtUtc"></label><label>Product ID<input [(ngModel)]="item.catalogProductId"></label><label>Variant ID<input [(ngModel)]="item.productVariantId"></label><label>SKU<input [(ngModel)]="item.sku"></label><label>Description<input [(ngModel)]="item.description"></label><label>Quantity<input type="number" [(ngModel)]="item.quantity"></label><label>Unit<input [(ngModel)]="item.unit"></label><label>Unit price<input type="number" [(ngModel)]="item.unitPrice"></label><label>Discount<input type="number" [(ngModel)]="item.discount"></label><label>Tax<input type="number" [(ngModel)]="item.tax"></label></div>
      <div class="form" *ngIf="formType==='fulfillment'"><label>Sales order ID<input [(ngModel)]="form.salesOrderId"></label><label>Type<select [(ngModel)]="form.type"><option>Pickup</option><option>Delivery</option></select></label><label>Pickup facility ID<input [(ngModel)]="form.pickupFacilityId"></label><label>Delivery method<select [(ngModel)]="form.deliveryMethod"><option>CompanyLogistics</option><option>ExternalCarrier</option></select></label></div>
      <div class="form" *ngIf="formType==='reservation'"><label>Stock balance ID<input [(ngModel)]="form.stockBalanceId"></label><label>Quantity<input type="number" [(ngModel)]="form.quantity"></label><label>Reference<input [(ngModel)]="form.reference"></label></div>
      <div class="form" *ngIf="formType==='movement'"><label>Product ID<input [(ngModel)]="form.catalogProductId"></label><label>Quantity<input type="number" [(ngModel)]="form.quantity"></label><label>From facility ID<input [(ngModel)]="form.fromFacilityId"></label><label>To facility ID<input [(ngModel)]="form.toFacilityId"></label></div>
      <div class="form" *ngIf="formType==='shipment'"><label>Fulfillment ID<input [(ngModel)]="form.fulfillmentId"></label><label>Carrier<input [(ngModel)]="form.carrierName"></label><label>Tracking number<input [(ngModel)]="form.trackingNumber"></label><label>ETA<input type="datetime-local" [(ngModel)]="form.estimatedDeliveryAtUtc"></label></div>
      <div class="form" *ngIf="formType==='payment'"><label>Amount<input type="number" [(ngModel)]="form.amount"></label><label>Currency<input [(ngModel)]="form.currency"></label><label>Method<select [(ngModel)]="form.method"><option>Cash</option><option>BankTransfer</option><option>Card</option><option>Online</option><option>Other</option></select></label><label>Order ID<input [(ngModel)]="form.salesOrderId"></label></div>
      <div class="form" *ngIf="formType==='capability'"><label>Capability<input [(ngModel)]="form.name"></label><label>Description<input [(ngModel)]="form.description"></label><label class="check"><input type="checkbox" [(ngModel)]="form.isActive"> Active</label></div>
      <div class="capabilities" *ngIf="formType==='capabilities'"><article *ngFor="let c of capabilities"><b>{{c.name}}</b><span>{{c.description||'Facility capability'}}</span></article><div class="state compact" *ngIf="!capabilities.length">No capabilities configured.</div></div>
      <div class="modal-actions"><button type="button" class="quiet-action" (click)="close()">Cancel</button><button type="button" class="primary-action" *ngIf="formType!=='capabilities'" (click)="save()" [disabled]="saving">{{saving?'Saving…':'Save'}}</button><button type="button" class="primary-action" *ngIf="formType==='capabilities'" (click)="formType='capability';modalTitle='Add capability';form={}">＋ Add capability</button></div>
    </section></div>
    <div class="overlay" *ngIf="statusModal"><section class="drawer compact-drawer"><header><div><small>WORKFLOW</small><h2>Update {{statusKind}}</h2></div><button type="button" class="close" (click)="statusModal=false">×</button></header><label class="single-field">Status<select [(ngModel)]="nextStatus"><option *ngFor="let s of statusOptions">{{s}}</option></select></label><div class="modal-actions"><button type="button" class="quiet-action" (click)="statusModal=false">Cancel</button><button type="button" class="primary-action" (click)="saveStatus()">Update</button></div></section></div>
    <div class="overlay" *ngIf="rowActionModal"><section class="drawer compact-drawer"><header><div><small>RENOVA / ENTERPRISE</small><h2>Record actions</h2></div><button type="button" class="close" (click)="rowActionModal=false">×</button></header><div class="action-menu"><button type="button" *ngIf="section==='facilities'" (click)="rowActionModal=false;openEditFacility(selectedRow)">Edit facility</button><button type="button" *ngIf="section==='facilities'" (click)="rowActionModal=false;openCapabilities(selectedRow)">Manage capabilities</button><button type="button" *ngIf="hasStatus" (click)="rowActionModal=false;openStatus(selectedRow)">Update status</button><button type="button" (click)="rowActionModal=false">Close</button></div></section></div>
  `,
  styles: [``]
})
export class EnterpriseOperationsPage implements OnInit {
  private readonly api=inject(ApiService); private readonly route=inject(ActivatedRoute);
  section='facilities'; rows:any[]=[]; keys:string[]=[]; columns:string[]=[]; loading=false; error=''; modal=false; statusModal=false; rowActionModal=false; saving=false;
  formType=''; modalTitle=''; form:any={}; item:any={}; capabilities:any[]=[]; selectedFacilityId=''; selectedRow:any=null; statusKind=''; nextStatus=''; statusOptions:string[]=[];
  search=''; statusFilter=''; clientFilter=''; dateFrom=''; dateTo=''; page=1; pageSize=10; selected=new Set<any>();
  readonly tenant=localStorage.getItem('qai-tenant')||'renova';
  readonly tabs:Tab[]=[
    {key:'facilities',label:'Objektet',endpoint:'enterprise/facilities',create:'facility'}, {key:'customers',label:'Klientët',endpoint:'enterprise/customers',create:'customer'}, {key:'price-lists',label:'Price Lists',endpoint:'enterprise/price-lists',create:'priceList'}, {key:'orders',label:'Porositë',endpoint:'enterprise/orders',create:'order',status:['Draft','Submitted','Confirmed','PartiallyFulfilled','Fulfilled','Cancelled']}, {key:'fulfillments',label:'Furnizimi',endpoint:'enterprise/fulfillments',create:'fulfillment',status:['pending','ready','picked-up','delivered','completed','cancelled']}, {key:'inventory',label:'Inventari',endpoint:'enterprise/stock'}, {key:'reservations',label:'Reservations',endpoint:'enterprise/reservations',create:'reservation'}, {key:'movements',label:'Stock Movements',endpoint:'enterprise/movements',create:'movement',status:['Requested','Approved','Prepared','Dispatched','InTransit','Received','Completed','Cancelled']}, {key:'warehousing',label:'Warehousing',endpoint:'enterprise/facilities'}, {key:'distribution',label:'Shpërndarja',endpoint:'enterprise/facilities'}, {key:'logistics',label:'Logistics',endpoint:'enterprise/shipments',create:'shipment',status:['Planned','Prepared','Dispatched','InTransit','Delivered','Cancelled']}, {key:'routes',label:'Routes',endpoint:'enterprise/routes'}, {key:'documents',label:'Dokumente',endpoint:'enterprise/documents'}, {key:'payments',label:'Payments',endpoint:'enterprise/payments',create:'payment',status:['Pending','Requested','PartiallyPaid','Paid','Failed','Refunded','Cancelled']}
  ];
  readonly labels:any={facilities:['Objektet','Menaxhoni objektet, kapacitetet dhe statusin operacional.'],customers:['Klientët','Menaxhoni klientët dhe llogaritë komerciale.'],'price-lists':['Price Lists','Commercial pricing and price-list items.'],orders:['Porositë','Menaxhoni të gjitha porositë, statuset dhe partnerët tuaj.'],fulfillments:['Furnizimi','Pickup and delivery execution.'],inventory:['Inventari','Stock balances and availability.'],reservations:['Reservations','Reserved stock against commercial demand.'],movements:['Stock Movements','Controlled facility-to-facility stock lifecycle.'],warehousing:['Warehousing','Warehouse operations using the facility network.'],distribution:['Shpërndarja','Distribution points and local fulfillment.'],logistics:['Logistics','Shipment and delivery execution.'],routes:['Routes','Route plans from the enterprise API.'],documents:['Dokumente','Proforma, invoice, receipt and credit-note records.'],payments:['Payments','Payment requests and financial status.']};
  ngOnInit(){this.route.paramMap.subscribe(p=>{this.section=p.get('section')||'facilities';this.resetView();this.load()})}
  resetView(){this.search='';this.statusFilter='';this.clientFilter='';this.dateFrom='';this.dateTo='';this.page=1;this.selected.clear()}
  get title(){return this.labels[this.section]?.[0]||this.section} get subtitle(){return this.labels[this.section]?.[1]||''} get tab(){return this.tabs.find(x=>x.key===this.section)||this.tabs[0]} get canCreate(){return !!this.tab.create} get hasStatus(){return !!this.tab.status}
  get statusValues(){return Array.from(new Set((this.rows||[]).map(r=>r?.status).filter(Boolean).map(String)))}
  get clientValues(){return Array.from(new Set((this.rows||[]).map(r=>r?.companyName||r?.clientName||r?.companyId||r?.customerAccountId).filter(Boolean).map(String))).sort()}
  get filteredRows(){const q=this.search.trim().toLowerCase();const from=this.dateFrom?new Date(this.dateFrom+'T00:00:00'):null;const to=this.dateTo?new Date(this.dateTo+'T23:59:59'):null;return this.rows.filter(r=>{const text=Object.values(r||{}).join(' ').toLowerCase();const client=String(r?.companyName||r?.clientName||r?.companyId||r?.customerAccountId||'');const dates=Object.entries(r||{}).filter(([k,v])=>/AtUtc$|Date$/i.test(k)&&v).map(([,v])=>new Date(String(v))).filter(d=>!isNaN(d.getTime()));const inDate=!from&&!to||dates.length===0||dates.some(d=>(!from||d>=from)&&(!to||d<=to));return(!q||text.includes(q))&&(!this.statusFilter||String(r?.status||'')===this.statusFilter)&&(!this.clientFilter||client===this.clientFilter)&&inDate})}
  get pageCount(){return Math.max(1,Math.ceil(this.filteredRows.length/this.pageSize))} get pageStart(){return Math.min((this.page-1)*this.pageSize,this.filteredRows.length)} get pageEnd(){return Math.min(this.pageStart+this.pageSize,this.filteredRows.length)} get pagedRows(){if(this.page>this.pageCount)this.page=this.pageCount;return this.filteredRows.slice(this.pageStart,this.pageEnd)} get pageNumbers(){return Array.from({length:this.pageCount},(_,i)=>i+1).slice(Math.max(0,this.page-3),Math.min(this.pageCount,this.page+2))} get hasFilters(){return !!(this.search||this.statusFilter||this.clientFilter||this.dateFrom||this.dateTo)} get allPageSelected(){return this.pagedRows.length>0&&this.pagedRows.every(r=>this.selected.has(r))}
  get summaryCards():MetricCard[]{const all=this.rows||[];const count=(names:string[])=>all.filter(r=>names.includes(String(r?.status))).length;const total=all.length;switch(this.section){case'orders':return[{label:'Totali i Porosive',value:total,tone:'blue',icon:'🛒',note:'të gjitha porositë'},{label:'Në Proces',value:count(['Draft','Submitted','Confirmed','PartiallyFulfilled']),tone:'amber',icon:'◷',note:'në rrjedhën operative'},{label:'Dërguar',value:count(['Dispatched','InTransit','Delivered']),tone:'green',icon:'▣',note:'në dërgesë'},{label:'Të Përfunduara',value:count(['Fulfilled','Completed']),tone:'violet',icon:'✓',note:'workflow i përfunduar'},{label:'Të Anuluara',value:count(['Cancelled','cancelled']),tone:'rose',icon:'△',note:'të anuluara'}];case'fulfillments':case'logistics':return[{label:'Totali',value:total,tone:'blue',icon:'▣',note:'regjistrime aktive'},{label:'Në Proces',value:count(['pending','ready','Planned','Prepared']),tone:'amber',icon:'◷',note:'në proces'},{label:'Dërguar',value:count(['picked-up','Dispatched','InTransit']),tone:'green',icon:'▣',note:'në transport'},{label:'Të Përfunduara',value:count(['delivered','completed','Delivered']),tone:'violet',icon:'✓',note:'të përfunduara'},{label:'Të Anuluara',value:count(['cancelled','Cancelled']),tone:'rose',icon:'△',note:'të anuluara'}];default:return[{label:'Total',value:total,tone:'blue',icon:'▦',note:'records in workspace'},{label:'Aktive',value:all.filter(r=>r?.isActive===true||!('isActive'in r)).length,tone:'green',icon:'✓',note:'active records'},{label:'Në Proces',value:count(['Draft','Submitted','Pending','Requested','InTransit']),tone:'amber',icon:'◷',note:'workflow records'},{label:'Përfunduara',value:count(['Completed','Fulfilled','Paid','Delivered']),tone:'violet',icon:'✓',note:'completed records'},{label:'Me Status',value:all.filter(r=>r?.status).length,tone:'rose',icon:'◎',note:'tracked workflow'}]}}
  tabIcon(key:string){const icons:any={facilities:'⌂',customers:'♧','price-lists':'≋',orders:'▣',fulfillments:'◫',inventory:'▱',reservations:'□',movements:'✣',warehousing:'▥',distribution:'▣',logistics:'▤',routes:'⌁',documents:'▤',payments:'▰'};return icons[key]||'•'}
  statusTone(value:any){const s=String(value||'').toLowerCase();if(['completed','fulfilled','paid','delivered','ready'].some(x=>s.includes(x)))return'green';if(['draft','submitted','confirmed','dispatched','intransit','picked-up'].some(x=>s.includes(x)))return'blue';if(['pending','requested','prepared','partially'].some(x=>s.includes(x)))return'amber';if(['cancelled','failed','refunded'].some(x=>s.includes(x)))return'rose';return'violet'}
  clearFilters(){this.resetView()}
  load(){this.loading=true;this.error='';this.api.get<any[]>(this.tab.endpoint).subscribe({next:r=>{this.rows=Array.isArray(r)?r:[];if(this.section==='warehousing')this.rows=this.rows.filter(x=>x.type==='Warehouse');if(this.section==='distribution')this.rows=this.rows.filter(x=>x.type==='DistributionPoint');this.configure();this.page=1;this.loading=false},error:(e:unknown)=>{const err=e as {error?:{detail?:string;title?:string}};this.rows=[];this.error=err.error?.detail||err.error?.title||'Renova Enterprise API is unavailable.';this.loading=false}})}
  configure(){const preferred:any={facilities:['name','code','type','countryCode','city','capacity','isActive'],customers:['companyId','creditLimit','paymentTermsDays','isActive'],'price-lists':['code','name','currency','isActive'],orders:['number','channel','currency','status','grandTotal','requestedDeliveryAtUtc'],fulfillments:['salesOrderId','type','status','deliveryMethod','pickupFacilityId','completedAtUtc'],inventory:['facilityId','catalogProductId','productVariantId','onHand','reserved','available'],reservations:['stockBalanceId','quantity','status','reference'],movements:['number','fromFacilityId','toFacilityId','quantity','status','dispatchedAtUtc','receivedAtUtc'],warehousing:['name','code','type','countryCode','city','capacity','isActive'],distribution:['name','code','type','countryCode','city','capacity','isActive'],logistics:['number','fulfillmentId','status','estimatedDeliveryAtUtc','deliveredAtUtc'],routes:['number','status','plannedStartAtUtc','plannedEndAtUtc'],documents:['number','type','salesOrderId','currency','total','status'],payments:['amount','currency','method','status','requestedAtUtc','paidAtUtc']};const sample=this.rows[0]||{};this.keys=(preferred[this.section]||Object.keys(sample)).filter((k:string)=>Object.prototype.hasOwnProperty.call(sample,k)).slice(0,8);if(!this.keys.length)this.keys=Object.keys(sample).slice(0,8);this.columns=this.keys.map(x=>x.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase()))}
  display(row:any,key:string){const v=row?.[key];if(v===null||v===undefined||v==='')return '—';if(typeof v==='boolean')return v?'Yes':'No';if(String(v).includes('T')&&/AtUtc$/i.test(key))return new Date(v).toLocaleString();return String(v)}
  openCreate(){this.modal=true;this.formType=this.tab.create||'';this.modalTitle='Create '+this.title;this.form={currency:'EUR',countryCode:'MK',type:'Factory',channel:'B2C',method:'Cash',deliveryMethod:'CompanyLogistics',isActive:true};this.item={quantity:1,unit:'unit',unitPrice:0,discount:0,tax:0}}
  openEditFacility(row:any){this.selectedRow=row;this.modal=true;this.formType='facility';this.modalTitle='Edit facility';this.form={...row}}
  openCapabilities(row:any){this.modal=true;this.formType='capabilities';this.modalTitle='Facility capabilities';this.selectedFacilityId=row.id;this.api.get<any[]>(`enterprise/facilities/${row.id}/capabilities`).subscribe({next:r=>this.capabilities=Array.isArray(r)?r:[],error:()=>this.capabilities=[]})}
  openRowActions(row:any){this.selectedRow=row;this.rowActionModal=true}
  isSelected(row:any){return this.selected.has(row)} trackRow(_:number,row:any){return row?.id||row?.number||row?.code||_}
  toggleRow(row:any){this.selected.has(row)?this.selected.delete(row):this.selected.add(row)} togglePage(event:any){const checked=!!event.target.checked;this.pagedRows.forEach(r=>checked?this.selected.add(r):this.selected.delete(r))}
  goPage(p:number){this.page=Math.max(1,Math.min(this.pageCount,p));this.selected.clear()} previousPage(){this.goPage(this.page-1)} nextPage(){this.goPage(this.page+1)}
  exportCsv(){const rows=this.filteredRows;if(!rows.length)return;const header=this.keys.map(k=>this.columns[this.keys.indexOf(k)]);const csv=[header,...rows.map(r=>this.keys.map(k=>String(this.display(r,k)).replace(/"/g,'""')))].map(r=>r.map(v=>'"'+v+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`renova-${this.section}.csv`;a.click();URL.revokeObjectURL(url)}
  close(){this.modal=false}
  save(){this.saving=true;let request:any=this.form;let call:any;if(this.formType==='facility')call=this.form.id?this.api.put(`enterprise/facilities/${this.form.id}`,request):this.api.post('enterprise/facilities',request);else if(this.formType==='customer')call=this.api.post('enterprise/customers',request);else if(this.formType==='priceList')call=this.api.post('enterprise/price-lists',request);else if(this.formType==='order')call=this.api.post('enterprise/orders',{...this.form,items:[this.item]});else if(this.formType==='fulfillment')call=this.api.post('enterprise/fulfillments',request);else if(this.formType==='reservation')call=this.api.post('enterprise/reservations',request);else if(this.formType==='movement')call=this.api.post('enterprise/movements',request);else if(this.formType==='shipment')call=this.api.post('enterprise/shipments',request);else if(this.formType==='payment')call=this.api.post('enterprise/payments',request);else if(this.formType==='capability')call=this.api.post(`enterprise/facilities/${this.selectedFacilityId}/capabilities`,request);else {this.saving=false;return}call.subscribe({next:()=>{this.saving=false;this.modal=false;this.load()},error:(e:unknown)=>{const err=e as {error?:{detail?:string}};this.saving=false;this.error=err.error?.detail||'Save failed.'}})}
  openStatus(row:any){this.selectedFacilityId=row.id;this.statusKind=this.section==='orders'?'order':this.section==='fulfillments'?'fulfillment':this.section==='movements'?'movement':this.section==='logistics'?'shipment':'payment';this.statusOptions=this.tab.status||[];this.nextStatus=String(row.status);this.statusModal=true}
  saveStatus(){const base:any={orders:'enterprise/orders',fulfillments:'enterprise/fulfillments',movements:'enterprise/movements',logistics:'enterprise/shipments',payments:'enterprise/payments'};const endpoint=base[this.section];if(!endpoint)return;this.api.post(`${endpoint}/${this.selectedFacilityId}/status`,this.nextStatus).subscribe({next:()=>{this.statusModal=false;this.load()},error:(e:unknown)=>{const err=e as {error?:{detail?:string}};this.error=err.error?.detail||'Status update failed.'}})}
}
