import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/api.service';
import { PageHeader } from '../../shared/ui';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink,PageHeader],template:`
<qai-page-header [title]="title" [subtitle]="subtitle"><a routerLink="/enterprise" class="back">← Renova Operations</a><button class="secondary" (click)="load()">↻ Refresh</button><button class="primary" (click)="openCreate()" *ngIf="canCreate">+ New</button></qai-page-header>
<nav class="tabs"><a *ngFor="let t of tabs" [routerLink]="'/enterprise/'+t.key" [class.active]="section===t.key">{{t.label}}</a></nav>
<section class="meta"><div><span>RENOVA WORKSPACE</span><b>{{tenant}}</b></div><div><span>API SOURCE</span><b>Enterprise API</b></div><div><span>RECORDS</span><b>{{rows.length}}</b></div></section>
<section class="toolbar" *ngIf="section==='warehousing'||section==='distribution'"><b>{{section==='warehousing'?'Warehouse view':'Distribution view'}}</b><span>These views use the API Facility model and filter by facility type. No separate endpoint is fabricated.</span></section>
<section class="panel"><div *ngIf="loading" class="state">Loading Renova data…</div><div *ngIf="error" class="error">{{error}}</div><div *ngIf="!loading&&!error&&rows.length" class="table"><table><thead><tr><th *ngFor="let c of columns">{{c}}</th><th *ngIf="hasStatus">Actions</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let k of keys">{{display(row,k)}}</td><td *ngIf="hasStatus"><button class="link" (click)="advance(row)">Update status</button></td></tr></tbody></table></div><div *ngIf="!loading&&!error&&!rows.length" class="empty"><b>No Renova records yet</b><span>The tenant API returned no records for this module.</span></div></section>
<div class="drawer" *ngIf="modal"><div class="modal"><div class="modal-head"><div><small>RENOVA / ENTERPRISE</small><h3>{{modalTitle}}</h3></div><button class="icon" (click)="close()">×</button></div>
<div class="form" *ngIf="formType==='facility'"><label>Code<input [(ngModel)]="form.code"></label><label>Name<input [(ngModel)]="form.name"></label><label>Type<select [(ngModel)]="form.type"><option>Factory</option><option>Warehouse</option><option>DistributionPoint</option><option>Office</option><option>Other</option></select></label><label>Country<input [(ngModel)]="form.countryCode"></label><label>City<input [(ngModel)]="form.city"></label><label>Address<input [(ngModel)]="form.address"></label><label>Capacity<input type="number" [(ngModel)]="form.capacity"></label></div>
<div class="form" *ngIf="formType==='customer'"><label>Company ID<input [(ngModel)]="form.companyId" placeholder="GUID"></label><label>Credit limit<input type="number" [(ngModel)]="form.creditLimit"></label><label>Payment terms days<input type="number" [(ngModel)]="form.paymentTermsDays"></label></div>
<div class="form" *ngIf="formType==='priceList'"><label>Code<input [(ngModel)]="form.code"></label><label>Name<input [(ngModel)]="form.name"></label><label>Currency<input [(ngModel)]="form.currency"></label></div>
<div class="form" *ngIf="formType==='payment'"><label>Amount<input type="number" [(ngModel)]="form.amount"></label><label>Currency<input [(ngModel)]="form.currency"></label><label>Method<select [(ngModel)]="form.method"><option>Cash</option><option>BankTransfer</option><option>Card</option><option>Online</option><option>Other</option></select></label><label>Order ID<input [(ngModel)]="form.salesOrderId" placeholder="Optional GUID"></label></div>
<div class="form" *ngIf="formType==='movement'"><label>Quantity<input type="number" [(ngModel)]="form.quantity"></label><label>Product ID<input [(ngModel)]="form.catalogProductId"></label><label>From facility<input [(ngModel)]="form.fromFacilityId"></label><label>To facility<input [(ngModel)]="form.toFacilityId"></label></div>
<div class="form" *ngIf="formType==='reservation'"><label>Stock balance ID<input [(ngModel)]="form.stockBalanceId"></label><label>Quantity<input type="number" [(ngModel)]="form.quantity"></label><label>Reference<input [(ngModel)]="form.reference"></label></div>
<div class="form" *ngIf="formType==='fulfillment'"><label>Sales order ID<input [(ngModel)]="form.salesOrderId"></label><label>Type<select [(ngModel)]="form.type"><option>Pickup</option><option>Delivery</option></select></label><label>Pickup facility ID<input [(ngModel)]="form.pickupFacilityId"></label><label>Delivery method<select [(ngModel)]="form.deliveryMethod"><option>CompanyLogistics</option><option>ExternalCarrier</option></select></label></div>
<div class="form" *ngIf="formType==='shipment'"><label>Fulfillment ID<input [(ngModel)]="form.fulfillmentId"></label><label>Carrier<input [(ngModel)]="form.carrierName"></label><label>Tracking number<input [(ngModel)]="form.trackingNumber"></label><label>ETA<input type="datetime-local" [(ngModel)]="form.estimatedDeliveryAtUtc"></label></div>
<div class="form" *ngIf="formType==='order'"><label>Channel<select [(ngModel)]="form.channel"><option>B2C</option><option>B2B</option><option>Distributor</option><option>Partner</option></select></label><label>Currency<input [(ngModel)]="form.currency"></label><label>Company ID<input [(ngModel)]="form.companyId"></label><label>Product ID<input [(ngModel)]="form.catalogProductId"></label><label>SKU<input [(ngModel)]="form.sku"></label><label>Description<input [(ngModel)]="form.description"></label><label>Quantity<input type="number" [(ngModel)]="form.quantity"></label><label>Unit price<input type="number" [(ngModel)]="form.unitPrice"></label></div>
<div class="modal-actions"><button class="secondary" (click)="close()">Cancel</button><button class="primary" (click)="save()" [disabled]="saving">{{saving?'Saving…':'Save'}}</button></div></div></div>
<div class="drawer" *ngIf="statusModal"><div class="modal compact"><div class="modal-head"><div><small>STATUS WORKFLOW</small><h3>Update {{statusKind}}</h3></div><button class="icon" (click)="statusModal=false">×</button></div><label>Status<select [(ngModel)]="nextStatus"><option *ngFor="let s of statusOptions">{{s}}</option></select></label><div class="modal-actions"><button class="secondary" (click)="statusModal=false">Cancel</button><button class="primary" (click)="saveStatus()">Update</button></div></div></div>
`,styles:[`:host{display:block;color:#172033}.back,.secondary,.primary,.link,.icon{padding:8px 11px;border:1px solid #dfe5ed;border-radius:8px;background:#fff;color:#315fbd;text-decoration:none;font-size:9px;cursor:pointer}.primary{background:#c62828;border-color:#c62828;color:#fff;font-weight:800}.tabs{display:flex;gap:6px;overflow:auto;padding:2px 0 13px}.tabs a{white-space:nowrap;padding:8px 11px;border:1px solid #dfe5ed;border-radius:8px;color:#66748b;background:#fff;text-decoration:none;font-size:9px}.tabs a.active{color:#c62828;border-color:#efb8b8;background:#fff7f7;font-weight:800}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:14px}.meta div,.toolbar{padding:13px;border:1px solid #dfe5ed;border-radius:11px;background:#fff}.meta span{display:block;font-size:8px;color:#7b8798;letter-spacing:.7px}.meta b{display:block;margin-top:6px;font-size:12px}.toolbar{margin-bottom:14px;display:grid;gap:4px}.toolbar span{color:#7b8798;font-size:9px}.panel{border:1px solid #dfe5ed;border-radius:13px;overflow:hidden;background:#fff;min-height:260px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th{text-align:left;padding:10px;background:#f5f7f9;border-bottom:1px solid #dfe5ed;color:#66748b;font-size:8px;white-space:nowrap}td{padding:11px 10px;border-bottom:1px solid #edf0f4;font-size:9px;white-space:nowrap}.link{border:0;background:transparent;color:#c62828;padding:4px}.state,.empty,.error{padding:30px;font-size:10px}.empty{text-align:center;display:grid;gap:5px}.empty span{color:#7b8798}.error{background:#fff1f2;color:#9f1239}.drawer{position:fixed;inset:0;background:#17203355;display:flex;justify-content:flex-end;z-index:50}.modal{width:min(520px,100%);height:100%;background:#fff;padding:24px;box-shadow:-10px 0 30px #0002;overflow:auto}.modal.compact{height:auto;align-self:center;border-radius:14px;margin:20px}.modal-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:20px}.modal-head small{font-size:8px;letter-spacing:1px;color:#c62828}.modal-head h3{margin:5px 0;font-size:20px}.icon{font-size:18px;padding:4px 9px}.form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.form label,.compact>label{display:grid;gap:5px;font-size:9px;color:#66748b;font-weight:700}.form input,.form select,.compact select{width:100%;box-sizing:border-box;border:1px solid #dfe5ed;border-radius:8px;padding:9px;font:inherit}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:22px}@media(max-width:700px){.meta{grid-template-columns:1fr}.form{grid-template-columns:1fr}.modal{padding:18px}}`]
})
export class EnterpriseModulePage implements OnInit {
 private readonly api=inject(ApiService); private readonly route=inject(ActivatedRoute); section='facilities'; rows:any[]=[]; keys:string[]=[]; columns:string[]=[]; loading=false; error=''; tenant=localStorage.getItem('qai-tenant')||'renova'; modal=false; statusModal=false; saving=false; formType=''; modalTitle=''; form:any={}; statusKind=''; nextStatus=''; selected:any=null; statusOptions:string[]=[];
 readonly tabs=[{key:'facilities',label:'Facilities'},{key:'customers',label:'Customers'},{key:'price-lists',label:'Price Lists'},{key:'orders',label:'Ordering'},{key:'fulfillments',label:'Fulfillment'},{key:'inventory',label:'Inventory'},{key:'reservations',label:'Reservations'},{key:'movements',label:'Stock Movements'},{key:'warehousing',label:'Warehousing'},{key:'distribution',label:'Distribution'},{key:'logistics',label:'Logistics'},{key:'routes',label:'Routes'},{key:'documents',label:'Documents'},{key:'payments',label:'Payments'}];
 readonly labels:any={facilities:['Facilities','Factories, warehouses and distribution points.'],customers:['Customers','Renova customer and commercial accounts.'],'price-lists':['Price Lists','Commercial pricing for products and customers.'],orders:['Ordering','B2C, B2B, distributor and partner orders.'],fulfillments:['Fulfillment','Pickup and delivery execution.'],inventory:['Inventory','Stock balances and availability.'],reservations:['Reservations','Reserved stock against commercial demand.'],movements:['Stock Movements','Factory, warehouse and distribution transfers.'],warehousing:['Warehousing','Facility records filtered for warehouse operations.'],distribution:['Distribution','Facility records filtered for distribution points.'],logistics:['Logistics','Shipments and delivery execution.'],routes:['Routes','Route plans returned by the enterprise API.'],documents:['Documents','Proforma, invoice, receipt and credit-note records.'],payments:['Payments','Payment requests and financial status.']};
 ngOnInit(){this.route.paramMap.subscribe(p=>{this.section=p.get('section')||'facilities';this.load()})} get title(){return this.labels[this.section]?.[0]||this.section} get subtitle(){return this.labels[this.section]?.[1]||''}
 get canCreate(){return ['facilities','customers','price-lists','orders','fulfillments','reservations','movements','logistics','payments'].includes(this.section)} get hasStatus(){return ['orders','fulfillments','movements','logistics','payments'].includes(this.section)}
 get endpoint(){const e:any={facilities:'enterprise/facilities',customers:'enterprise/customers','price-lists':'enterprise/price-lists',orders:'enterprise/orders',fulfillments:'enterprise/fulfillments',inventory:'enterprise/stock',reservations:'enterprise/reservations',movements:'enterprise/movements',warehousing:'enterprise/facilities',distribution:'enterprise/facilities',logistics:'enterprise/shipments',routes:'enterprise/routes',documents:'enterprise/documents',payments:'enterprise/payments'};return e[this.section]||'enterprise/facilities'}
 load(){this.loading=true;this.error='';this.api.get<any[]>(this.endpoint).subscribe({next:r=>{this.rows=Array.isArray(r)?r:[];if(this.section==='warehousing')this.rows=this.rows.filter(x=>x.type==='Warehouse');if(this.section==='distribution')this.rows=this.rows.filter(x=>x.type==='DistributionPoint');this.configure();this.loading=false},error:e=>{this.rows=[];this.error=e?.error?.detail||e?.error?.title||'Renova Enterprise API is unavailable.';this.loading=false}})}
 configure(){const preferred:any={facilities:['name','code','type','countryCode','city','capacity','isActive'],customers:['companyId','creditLimit','paymentTermsDays','isActive'],'price-lists':['code','name','currency','isActive'],orders:['number','channel','currency','status','grandTotal','requestedDeliveryAtUtc'],fulfillments:['salesOrderId','type','status','deliveryMethod','pickupFacilityId','completedAtUtc'],inventory:['facilityId','catalogProductId','productVariantId','onHand','reserved','available'],reservations:['stockBalanceId','quantity','status','reference'],movements:['number','fromFacilityId','toFacilityId','quantity','status','dispatchedAtUtc','receivedAtUtc'],warehousing:['name','code','type','countryCode','city','capacity','isActive'],distribution:['name','code','type','countryCode','city','capacity','isActive'],logistics:['number','fulfillmentId','status','estimatedDeliveryAtUtc','deliveredAtUtc'],routes:['number','status','plannedStartAtUtc','plannedEndAtUtc'],documents:['number','type','salesOrderId','currency','total','status'],payments:['amount','currency','method','status','requestedAtUtc','paidAtUtc']};const sample=this.rows[0]||{};this.keys=(preferred[this.section]||Object.keys(sample)).filter((k:string)=>Object.prototype.hasOwnProperty.call(sample,k)).slice(0,8);if(!this.keys.length)this.keys=Object.keys(sample).slice(0,8);this.columns=this.keys.map(x=>x.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase()))}
 display(row:any,key:string){const v=row?.[key];if(v===null||v===undefined||v==='')return '—';if(typeof v==='boolean')return v?'Yes':'No';if(key.toLowerCase().includes('at')&&String(v).includes('T'))return new Date(v).toLocaleString();return String(v)}
 openCreate(){this.modal=true;this.form={currency:'EUR',countryCode:'MK',type:'Factory',channel:'B2C',method:'Cash',deliveryMethod:'CompanyLogistics'};this.formType={facilities:'facility',customers:'customer','price-lists':'priceList',orders:'order',fulfillments:'fulfillment',reservations:'reservation',movements:'movement',logistics:'shipment',payments:'payment'}[this.section]||'';this.modalTitle='Create '+this.title}
 close(){this.modal=false}
 save(){this.saving=true;const f=this.form;let body:any=f;if(this.formType==='order')body={channel:f.channel,currency:f.currency,companyId:f.companyId||null,items:[{catalogProductId:f.catalogProductId,sku:f.sku,description:f.description,quantity:Number(f.quantity),unitPrice:Number(f.unitPrice),discount:0,tax:0,unit:'unit'}]};if(this.formType==='shipment')body={fulfillmentId:f.fulfillmentId,carrierName:f.carrierName,trackingNumber:f.trackingNumber,estimatedDeliveryAtUtc:f.estimatedDeliveryAtUtc};if(this.formType==='payment')body={amount:Number(f.amount),currency:f.currency,method:f.method,salesOrderId:f.salesOrderId||null};this.api.post(this.endpoint,body).subscribe({next:()=>{this.close();this.saving=false;this.load()},error:e=>{this.saving=false;this.error=e?.error?.detail||'Could not save Renova record.'}})}
 advance(row:any){this.selected=row;this.statusModal=true;this.statusKind=this.title;const current=String(row.status||'').toLowerCase();const opts:any={orders:['Submitted','Confirmed','PartiallyFulfilled','Fulfilled','Cancelled'],fulfillments:['pending','processing','completed','delivered','picked-up','cancelled'],movements:['Requested','Approved','Prepared','Dispatched','InTransit','Received','Completed','Cancelled'],logistics:['Planned','Prepared','Dispatched','InTransit','Delivered','Cancelled'],payments:['Pending','Requested','PartiallyPaid','Paid','Failed','Refunded','Cancelled']};this.statusOptions=opts[this.section]||[];this.nextStatus=this.statusOptions.find((x:string)=>x.toLowerCase()===current)||this.statusOptions[0]||''}
 saveStatus(){if(!this.selected||!this.nextStatus)return;const path:any={orders:`enterprise/orders/${this.selected.id}/status`,fulfillments:`enterprise/fulfillments/${this.selected.id}/status`,movements:`enterprise/movements/${this.selected.id}/status`,logistics:`enterprise/shipments/${this.selected.id}/status`,payments:`enterprise/payments/${this.selected.id}/status`};this.api.post(path[this.section],this.nextStatus).subscribe({next:()=>{this.statusModal=false;this.load()},error:e=>this.error=e?.error?.detail||'Status update failed.'})}
}
