import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ApiService } from '../../core/api.service';
import { PageHeader } from '../../shared/ui';

@Component({standalone:true,imports:[CommonModule,RouterLink,PageHeader],template:`
<qai-page-header [title]="title" [subtitle]="subtitle"><a routerLink="/enterprise" class="back">← Renova Operations</a><button (click)="load()">↻ Refresh</button></qai-page-header>
<nav class="tabs"><a routerLink="/enterprise/facilities" [class.active]="section==='facilities'">Facilities</a><a routerLink="/enterprise/orders" [class.active]="section==='orders'">Ordering</a><a routerLink="/enterprise/inventory" [class.active]="section==='inventory'">Inventory</a><a routerLink="/enterprise/warehousing" [class.active]="section==='warehousing'">Warehousing</a><a routerLink="/enterprise/distribution" [class.active]="section==='distribution'">Distribution</a><a routerLink="/enterprise/logistics" [class.active]="section==='logistics'">Logistics</a><a routerLink="/enterprise/payments" [class.active]="section==='payments'">Payments</a></nav>
<section class="meta"><div><span>RENOVA WORKSPACE</span><b>{{tenant}}</b></div><div><span>API SOURCE</span><b>Enterprise API</b></div><div><span>RECORDS</span><b>{{rows.length}}</b></div></section>
<section class="panel"><div *ngIf="loading" class="state">Loading Renova data…</div><div *ngIf="error" class="error">{{error}}</div><div *ngIf="!loading && !error && rows.length" class="table"><table><thead><tr><th *ngFor="let c of columns">{{c}}</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let k of keys">{{display(row,k)}}</td></tr></tbody></table></div><div *ngIf="!loading && !error && !rows.length" class="empty"><b>No Renova records yet</b><span>The tenant API returned no records for this module.</span></div></section>
`,styles:[`:host{display:block;color:#172033}.back,button{padding:8px 11px;border:1px solid #dfe5ed;border-radius:8px;background:#fff;color:#315fbd;text-decoration:none;font-size:9px}.tabs{display:flex;gap:6px;overflow:auto;padding:2px 0 13px}.tabs a{white-space:nowrap;padding:8px 11px;border:1px solid #dfe5ed;border-radius:8px;color:#66748b;background:#fff;text-decoration:none;font-size:9px}.tabs a.active{color:#c62828;border-color:#efb8b8;background:#fff7f7;font-weight:800}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:14px}.meta div{padding:13px;border:1px solid #dfe5ed;border-radius:11px;background:#fff}.meta span{display:block;font-size:8px;color:#7b8798;letter-spacing:.7px}.meta b{display:block;margin-top:6px;font-size:12px}.panel{border:1px solid #dfe5ed;border-radius:13px;overflow:hidden;background:#fff;min-height:260px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th{text-align:left;padding:10px;background:#f5f7f9;border-bottom:1px solid #dfe5ed;color:#66748b;font-size:8px;white-space:nowrap}td{padding:11px 10px;border-bottom:1px solid #edf0f4;font-size:9px;white-space:nowrap}.state,.empty,.error{padding:30px;font-size:10px}.empty{text-align:center;display:grid;gap:5px}.empty span{color:#7b8798}.error{background:#fff1f2;color:#9f1239}@media(max-width:700px){.meta{grid-template-columns:1fr}}`]
})
export class EnterpriseModulePage implements OnInit {
 private readonly api=inject(ApiService); private readonly route=inject(ActivatedRoute); section='facilities'; rows:any[]=[]; keys:string[]=[]; columns:string[]=[]; loading=false; error=''; tenant=localStorage.getItem('qai-tenant')||'renova';
 readonly labels:any={facilities:['Facilities','Factories, warehouses and distribution points.'],orders:['Ordering','B2C, B2B, distributor and partner orders.'],inventory:['Inventory','Stock balances, reservations and movements.'],warehousing:['Warehousing','Receiving, picking, packing and dispatch.'],distribution:['Distribution','Distribution points and local fulfillment.'],logistics:['Logistics','Shipments, routes and delivery execution.'],payments:['Payments & Documents','Proforma, invoices, receipts and payments.']};
 ngOnInit(){this.route.paramMap.subscribe(p=>{this.section=p.get('section')||'facilities';this.load()})}
 get title(){return this.labels[this.section]?.[0]||this.section}
 get subtitle(){return this.labels[this.section]?.[1]||''}
 load(){this.loading=true;this.error='';const endpoint:any={facilities:'enterprise/facilities',orders:'enterprise/orders',inventory:'enterprise/stock',warehousing:'enterprise/facilities',distribution:'enterprise/facilities',logistics:'enterprise/shipments',payments:'enterprise/payments'};this.api.get<any[]>(endpoint[this.section]||'enterprise/facilities').subscribe({next:r=>{this.rows=Array.isArray(r)?r:[];this.configure();this.loading=false},error:e=>{this.rows=[];this.error=e?.error?.detail||e?.error?.title||'Renova Enterprise API is unavailable.';this.loading=false}})}
 configure(){const preferred:any={facilities:['name','code','type','countryCode','city','capacity','isActive'],orders:['number','channel','currency','status','grandTotal','requestedDeliveryAtUtc'],inventory:['facilityId','catalogProductId','productVariantId','onHand','reserved','available'],warehousing:['name','code','type','countryCode','city','capacity','isActive'],distribution:['name','code','type','countryCode','city','capacity','isActive'],logistics:['number','fulfillmentId','status','estimatedDeliveryAtUtc','deliveredAtUtc'],payments:['id','paymentMethod','amount','currency','status','requestedAtUtc','paidAtUtc']};const sample=this.rows[0]||{};this.keys=(preferred[this.section]||Object.keys(sample)).filter((k:string)=>Object.prototype.hasOwnProperty.call(sample,k)).slice(0,8);if(!this.keys.length)this.keys=Object.keys(sample).slice(0,8);this.columns=this.keys.map(x=>x.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase()))}
 display(row:any,key:string){const v=row?.[key];if(v===null||v===undefined||v==='')return '—';if(typeof v==='boolean')return v?'Yes':'No';if(key.toLowerCase().includes('at')&&String(v).includes('T'))return new Date(v).toLocaleString();return String(v)}
}
