import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ApiService } from '../../core/api.service';
import { PageHeader } from '../../shared/ui';

@Component({standalone:true,imports:[CommonModule,RouterLink,PageHeader],template:`
<qai-page-header [title]="title" [subtitle]="subtitle"><a routerLink="/enterprise" class="back">← Command center</a><button type="button" (click)="load()">↻ {{t('refresh')}}</button></qai-page-header>
<div class="module-tabs"><a routerLink="/enterprise/facilities" [class.active]="section==='facilities'">Facilities</a><a routerLink="/enterprise/orders" [class.active]="section==='orders'">Ordering</a><a routerLink="/enterprise/inventory" [class.active]="section==='inventory'">Inventory</a><a routerLink="/enterprise/warehousing" [class.active]="section==='warehousing'">Warehousing</a><a routerLink="/enterprise/distribution" [class.active]="section==='distribution'">Distribution</a><a routerLink="/enterprise/logistics" [class.active]="section==='logistics'">Logistics</a><a routerLink="/enterprise/payments" [class.active]="section==='payments'">Payments</a></div>
<section class="summary"><div><span>{{t('records')}}</span><strong>{{rows.length}}</strong></div><div><span>{{t('tenant')}}</span><strong>{{tenant}}</strong></div><div><span>{{t('source')}}</span><strong>Enterprise API</strong></div></section>
<section class="panel"><header><div><span class="eyebrow">{{section.toUpperCase()}}</span><h2>{{title}}</h2><p>{{subtitle}}</p></div></header><div *ngIf="loading" class="state">{{t('loading')}}</div><div *ngIf="error" class="error">{{error}}</div><div *ngIf="!loading && !error && rows.length" class="table-wrap"><table><thead><tr><th *ngFor="let c of columns">{{c}}</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let c of keys">{{display(row,c)}}</td></tr></tbody></table></div><div *ngIf="!loading && !error && !rows.length" class="empty"><strong>{{t('empty')}}</strong><span>{{t('emptyText')}}</span></div></section>
`,styles:[`:host{display:block;color:#172033}.back{padding:8px 11px;border:1px solid #dfe5ed;border-radius:8px;text-decoration:none;color:#315fbd;background:#fff;font-size:9px}.module-tabs{display:flex;gap:6px;overflow:auto;padding:3px 0 13px}.module-tabs a{white-space:nowrap;padding:8px 10px;border:1px solid #dfe5ed;border-radius:8px;background:#fff;color:#66748b;text-decoration:none;font-size:9px}.module-tabs a.active{background:#edf4ff;color:#2563eb;border-color:#bfd0f5;font-weight:800}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin-bottom:14px}.summary div{padding:14px;border:1px solid #dfe5ed;border-radius:11px;background:linear-gradient(145deg,#fff,#f4f6f9)}.summary span{display:block;color:#7b8798;font-size:8px}.summary strong{display:block;margin-top:8px;font-size:16px}.panel{border:1px solid #dfe5ed;border-radius:14px;background:#f4f6f9;overflow:hidden}.panel header{padding:17px 18px;border-bottom:1px solid #dfe5ed;background:linear-gradient(180deg,#f7f9fb,#eef2f6)}.eyebrow{display:block;color:#66748b;font-size:8px;font-weight:800;letter-spacing:1px}.panel h2{margin:5px 0 4px;font-size:15px}.panel p{margin:0;color:#7b8798;font-size:9px}.table-wrap{overflow:auto;background:#fff}table{width:100%;border-collapse:collapse}th{text-align:left;padding:10px;color:#66748b;background:#f8fafc;border-bottom:1px solid #dfe5ed;font-size:8px;white-space:nowrap}td{padding:11px 10px;border-bottom:1px solid #edf0f4;font-size:9px;white-space:nowrap}.state,.empty,.error{padding:28px;font-size:10px}.empty{display:grid;gap:5px;text-align:center}.empty span{color:#7b8798}.error{color:#9f1239;background:#fff1f2}.panel .state{color:#66748b}@media(max-width:700px){.summary{grid-template-columns:1fr}.module-tabs{padding-bottom:10px}}`]
})
export class EnterpriseModulePage implements OnInit {
 private readonly api=inject(ApiService); private readonly route=inject(ActivatedRoute); section=''; rows:any[]=[]; keys:string[]=[]; columns:string[]=[]; loading=false; error=''; tenant=localStorage.getItem('qai-tenant')||'Workspace'; lang=localStorage.getItem('qai.admin.language')||'en';
 private readonly labels:any={en:{facilities:['Facilities','Factories, warehouses and distribution points.'],orders:['Ordering','B2C, B2B, distributor and partner orders.'],inventory:['Inventory','Stock balances, reservations and movements.'],warehousing:['Warehousing','Operational facilities and stock positions.'],distribution:['Distribution','Distribution facilities and local fulfillment.'],logistics:['Logistics','Shipments, routes and delivery execution.'],payments:['Payments & Documents','Payment requests and commercial documents.'],refresh:'Refresh',records:'Records',tenant:'Workspace',source:'Source',loading:'Loading enterprise data…',empty:'No records yet',emptyText:'The connected enterprise API returned no records for this tenant.'},mk:{facilities:['Капацитети','Фабрики, магацини и дистрибутивни точки.'],orders:['Нарачки','B2C, B2B, дистрибутерски и партнерски нарачки.'],inventory:['Залиха','Залиха, резервации и движења.'],warehousing:['Магацини','Оперативни капацитети и позиции на залиха.'],distribution:['Дистрибуција','Дистрибутивни капацитети и локално исполнување.'],logistics:['Логистика','Пратки, рути и испорака.'],payments:['Плаќања и документи','Барања за плаќање и комерцијални документи.'],refresh:'Освежи',records:'Записи',tenant:'Работен простор',source:'Извор',loading:'Се вчитуваат податоците…',empty:'Нема записи',emptyText:'Enterprise API не врати записи за овој tenant.'},sq:{facilities:['Kapacitetet','Fabrika, magazina dhe pika shpërndarjeje.'],orders:['Porositë','Porosi B2C, B2B, distributorë dhe partnerë.'],inventory:['Inventari','Stok, rezervime dhe lëvizje.'],warehousing:['Magazinat','Kapacitete operative dhe pozicione të stokut.'],distribution:['Shpërndarja','Kapacitete dhe përmbushje lokale.'],logistics:['Logjistika','Dërgesa, rrugë dhe dorëzim.'],payments:['Pagesat dhe dokumentet','Kërkesa pagesash dhe dokumente komerciale.'],refresh:'Rifresko',records:'Regjistrime',tenant:'Hapësira',source:'Burimi',loading:'Duke ngarkuar të dhënat…',empty:'Nuk ka regjistrime',emptyText:'Enterprise API nuk ktheu regjistrime për këtë tenant.'},de:{facilities:['Standorte','Fabriken, Lager und Distributionspunkte.'],orders:['Aufträge','B2C-, B2B-, Distributor- und Partneraufträge.'],inventory:['Bestand','Bestand, Reservierungen und Bewegungen.'],warehousing:['Lager','Operative Standorte und Bestandspositionen.'],distribution:['Distribution','Distributionsstandorte und lokale Erfüllung.'],logistics:['Logistik','Sendungen, Routen und Lieferung.'],payments:['Zahlungen & Dokumente','Zahlungsanfragen und Geschäftsdokumente.'],refresh:'Aktualisieren',records:'Datensätze',tenant:'Arbeitsbereich',source:'Quelle',loading:'Unternehmensdaten werden geladen…',empty:'Keine Datensätze',emptyText:'Die Enterprise API hat für diesen Mandanten keine Datensätze geliefert.'}};
 ngOnInit(){this.route.paramMap.subscribe(p=>{this.section=p.get('section')||'facilities';this.load()})}
 get title(){return this.labels[this.lang]?.[this.section]?.[0]||this.labels.en[this.section]?.[0]||this.section}
 get subtitle(){return this.labels[this.lang]?.[this.section]?.[1]||this.labels.en[this.section]?.[1]||''}
 t(k:string){return this.labels[this.lang]?.[k]||this.labels.en[k]||k}
 load(){this.loading=true;this.error='';const endpoint:any={facilities:'enterprise/facilities',orders:'enterprise/orders',inventory:'enterprise/stock',warehousing:'enterprise/facilities',distribution:'enterprise/facilities',logistics:'enterprise/shipments',payments:'enterprise/payments'};this.api.get<any[]>(endpoint[this.section]||'enterprise/facilities').subscribe({next:r=>{this.rows=Array.isArray(r)?r:[];this.configure();this.loading=false},error:e=>{this.rows=[];this.error=e?.error?.detail||e?.error?.title||'Enterprise API is unavailable.';this.loading=false}})}
 configure(){const preferred:any={facilities:['name','code','type','countryCode','city','capacity','isActive'],orders:['number','channel','currency','status','grandTotal','requestedDeliveryAtUtc'],inventory:['facilityId','catalogProductId','productVariantId','onHand','reserved','available'],warehousing:['name','code','type','countryCode','city','capacity','isActive'],distribution:['name','code','type','countryCode','city','capacity','isActive'],logistics:['number','fulfillmentId','status','estimatedDeliveryAtUtc','deliveredAtUtc'],payments:['id','paymentMethod','amount','currency','status','requestedAtUtc','paidAtUtc']};const sample=this.rows[0]||{};this.keys=(preferred[this.section]||Object.keys(sample)).filter((k:string)=>Object.prototype.hasOwnProperty.call(sample,k)).slice(0,8);if(!this.keys.length)this.keys=Object.keys(sample).slice(0,8);this.columns=this.keys.map(x=>x.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase()))}
 display(row:any,key:string){const value=row?.[key];if(value===null||value===undefined||value==='')return '—';if(typeof value==='boolean')return value?'Yes':'No';if(typeof value==='object')return JSON.stringify(value);if(key.toLowerCase().includes('at')&&String(value).includes('T'))return new Date(value).toLocaleString();return String(value)}
}
