import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

export type UiColumns = 1 | 2 | 3 | 4 | 5;
export interface UiAction { label: string; route?: string; }
export interface UiStep { number: string; category: string; title: string; subtitle: string; active?: boolean; }
export interface UiMetric { label: string; value: string | number; subtitle?: string; icon?: string; tone?: 'blue'|'violet'|'green'|'amber'|'rose'; action?: UiAction; }
export interface UiRow { label: string; detail?: string; value: string | number; }
export interface UiCardModel { eyebrow?: string; title: string; subtitle?: string; badge?: string; badgeTone?: 'neutral'|'success'|'info'|'warning'; rows?: UiRow[]; text?: string; action?: UiAction; }

@Component({selector:'qai-ui-section',standalone:true,imports:[CommonModule],template:`<section class="ui-section" [ngClass]="'columns-'+columns"><ng-content/></section>`,styles:[`:host{display:block;min-width:0}.ui-section{display:grid;gap:var(--wl-section-gap,14px);margin:0 0 var(--wl-section-margin,14px)}.columns-1{grid-template-columns:1fr}.columns-2{grid-template-columns:minmax(0,1.35fr) minmax(0,.65fr)}.columns-3{grid-template-columns:repeat(3,minmax(0,1fr))}.columns-4{grid-template-columns:repeat(4,minmax(0,1fr))}.columns-5{grid-template-columns:repeat(5,minmax(0,1fr))}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:var(--wl-kpi-gap,12px);margin-bottom:var(--wl-section-margin,14px)}.steps{display:grid;grid-template-columns:1fr 42px 1fr 42px 1fr 42px 1fr 42px 1fr;align-items:start;padding:var(--wl-steps-padding,18px)}.step{display:flex;gap:10px;min-width:0}.connector{height:1px;margin:15px 8px 0}.card{display:flex;flex-direction:column;min-width:0;height:100%;overflow:hidden}.card .body,.card .list,.card .table-wrap{display:grid;gap:var(--wl-card-gap,12px);min-width:0}.row,.item{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0}.copy{min-width:0;flex:1}.table-wrap{overflow:auto}table{width:100%;border-collapse:separate;border-spacing:0}.metric{position:relative;display:block;width:100%;min-width:0;box-sizing:border-box;text-align:left}.metric:before{content:'';position:absolute;inset:0 0 auto;height:3px}.top{display:flex;align-items:center;gap:9px}.icon{display:grid;place-items:center;flex:0 0 auto}@media(max-width:1100px){.columns-5,.columns-4,.columns-3{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.steps{grid-template-columns:repeat(5,1fr);gap:8px}.connector{display:none}}@media(max-width:680px){.ui-section,.metrics,.steps{grid-template-columns:1fr!important}}`]})
export class UiSection { @Input() columns:UiColumns=1; }

@Component({selector:'qai-ui-steps',standalone:true,imports:[CommonModule],template:`
<article class="surface" [attr.data-template]="template"><header><div><span class="eyebrow">{{eyebrow}}</span><h2>{{title}}</h2><p *ngIf="subtitle">{{subtitle}}</p></div><span class="badge" *ngIf="badge"><i></i>{{badge}}</span></header><div class="steps"><ng-container *ngFor="let step of steps;let last=last"><div class="step" [class.active]="step.active"><span class="node">{{step.number}}</span><div><small>{{step.category}}</small><strong>{{step.title}}</strong><em>{{step.subtitle}}</em></div></div><span class="connector" *ngIf="!last"></span></ng-container></div></article>`,
styles:[`:host{display:block;min-width:0}.ui-section{display:grid;gap:var(--wl-section-gap,14px);margin:0 0 var(--wl-section-margin,14px)}.columns-1{grid-template-columns:1fr}.columns-2{grid-template-columns:minmax(0,1.35fr) minmax(0,.65fr)}.columns-3{grid-template-columns:repeat(3,minmax(0,1fr))}.columns-4{grid-template-columns:repeat(4,minmax(0,1fr))}.columns-5{grid-template-columns:repeat(5,minmax(0,1fr))}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:var(--wl-kpi-gap,12px);margin-bottom:var(--wl-section-margin,14px)}.steps{display:grid;grid-template-columns:1fr 42px 1fr 42px 1fr 42px 1fr 42px 1fr;align-items:start;padding:var(--wl-steps-padding,18px)}.step{display:flex;gap:10px;min-width:0}.connector{height:1px;margin:15px 8px 0}.card{display:flex;flex-direction:column;min-width:0;height:100%;overflow:hidden}.card .body,.card .list,.card .table-wrap{display:grid;gap:var(--wl-card-gap,12px);min-width:0}.row,.item{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0}.copy{min-width:0;flex:1}.table-wrap{overflow:auto}table{width:100%;border-collapse:separate;border-spacing:0}.metric{position:relative;display:block;width:100%;min-width:0;box-sizing:border-box;text-align:left}.metric:before{content:'';position:absolute;inset:0 0 auto;height:3px}.top{display:flex;align-items:center;gap:9px}.icon{display:grid;place-items:center;flex:0 0 auto}@media(max-width:1100px){.columns-5,.columns-4,.columns-3{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.steps{grid-template-columns:repeat(5,1fr);gap:8px}.connector{display:none}}@media(max-width:680px){.ui-section,.metrics,.steps{grid-template-columns:1fr!important}}`]})
export class UiSteps { @Input() template='steps-01'; @Input() eyebrow='WORKFLOW'; @Input() title=''; @Input() subtitle=''; @Input() badge=''; @Input() steps:UiStep[]=[]; }

@Component({selector:'qai-ui-metrics',standalone:true,imports:[CommonModule],template:`<div class="metrics" [attr.data-template]="template"><button type="button" *ngFor="let item of items; let i = index" class="metric" (click)="action.emit(item.action?.route||'')"><span class="top"><span class="icon">{{item.icon||'•'}}</span><span>{{item.label}}</span></span><strong>{{item.value}}</strong><small>{{item.subtitle}}<i *ngIf="item.action">→</i></small></button></div>`,styles:[`:host{display:block;min-width:0}.ui-section{display:grid;gap:var(--wl-section-gap,14px);margin:0 0 var(--wl-section-margin,14px)}.columns-1{grid-template-columns:1fr}.columns-2{grid-template-columns:minmax(0,1.35fr) minmax(0,.65fr)}.columns-3{grid-template-columns:repeat(3,minmax(0,1fr))}.columns-4{grid-template-columns:repeat(4,minmax(0,1fr))}.columns-5{grid-template-columns:repeat(5,minmax(0,1fr))}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:var(--wl-kpi-gap,12px);margin-bottom:var(--wl-section-margin,14px)}.steps{display:grid;grid-template-columns:1fr 42px 1fr 42px 1fr 42px 1fr 42px 1fr;align-items:start;padding:var(--wl-steps-padding,18px)}.step{display:flex;gap:10px;min-width:0}.connector{height:1px;margin:15px 8px 0}.card{display:flex;flex-direction:column;min-width:0;height:100%;overflow:hidden}.card .body,.card .list,.card .table-wrap{display:grid;gap:var(--wl-card-gap,12px);min-width:0}.row,.item{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0}.copy{min-width:0;flex:1}.table-wrap{overflow:auto}table{width:100%;border-collapse:separate;border-spacing:0}.metric{position:relative;display:block;width:100%;min-width:0;box-sizing:border-box;text-align:left}.metric:before{content:'';position:absolute;inset:0 0 auto;height:3px}.top{display:flex;align-items:center;gap:9px}.icon{display:grid;place-items:center;flex:0 0 auto}@media(max-width:1100px){.columns-5,.columns-4,.columns-3{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.steps{grid-template-columns:repeat(5,1fr);gap:8px}.connector{display:none}}@media(max-width:680px){.ui-section,.metrics,.steps{grid-template-columns:1fr!important}}`]})
export class UiMetrics {
  @Input() template='kpi-01';
  @Input() items:UiMetric[]=[];
  @Output() action=new EventEmitter<string>();
}

@Component({selector:'qai-ui-card',standalone:true,imports:[CommonModule],template:`
<article class="card" [attr.data-template]="template"><header><div><span class="eyebrow" *ngIf="model.eyebrow">{{model.eyebrow}}</span><h3>{{model.title}}</h3><p *ngIf="model.subtitle">{{model.subtitle}}</p></div><span class="status" *ngIf="model.badge" [class.success]="model.badgeTone==='success'">{{model.badge}}</span></header><div class="body"><div class="row" *ngFor="let row of model.rows;let first=first" [class.first]="first"><span><small>{{row.label}}</small><em *ngIf="row.detail">{{row.detail}}</em></span><strong>{{row.value}}</strong></div><p class="text" *ngIf="model.text">{{model.text}}</p></div><footer *ngIf="model.action"><span>Next action</span><button type="button" (click)="action.emit(model.action?.route||'')">{{model.action?.label}} →</button></footer><ng-content/></article>`,
styles:[`:host{display:block;min-width:0}.ui-section{display:grid;gap:var(--wl-section-gap,14px);margin:0 0 var(--wl-section-margin,14px)}.columns-1{grid-template-columns:1fr}.columns-2{grid-template-columns:minmax(0,1.35fr) minmax(0,.65fr)}.columns-3{grid-template-columns:repeat(3,minmax(0,1fr))}.columns-4{grid-template-columns:repeat(4,minmax(0,1fr))}.columns-5{grid-template-columns:repeat(5,minmax(0,1fr))}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:var(--wl-kpi-gap,12px);margin-bottom:var(--wl-section-margin,14px)}.steps{display:grid;grid-template-columns:1fr 42px 1fr 42px 1fr 42px 1fr 42px 1fr;align-items:start;padding:var(--wl-steps-padding,18px)}.step{display:flex;gap:10px;min-width:0}.connector{height:1px;margin:15px 8px 0}.card{display:flex;flex-direction:column;min-width:0;height:100%;overflow:hidden}.card .body,.card .list,.card .table-wrap{display:grid;gap:var(--wl-card-gap,12px);min-width:0}.row,.item{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0}.copy{min-width:0;flex:1}.table-wrap{overflow:auto}table{width:100%;border-collapse:separate;border-spacing:0}.metric{position:relative;display:block;width:100%;min-width:0;box-sizing:border-box;text-align:left}.metric:before{content:'';position:absolute;inset:0 0 auto;height:3px}.top{display:flex;align-items:center;gap:9px}.icon{display:grid;place-items:center;flex:0 0 auto}@media(max-width:1100px){.columns-5,.columns-4,.columns-3{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.steps{grid-template-columns:repeat(5,1fr);gap:8px}.connector{display:none}}@media(max-width:680px){.ui-section,.metrics,.steps{grid-template-columns:1fr!important}}`]})
export class UiCard { @Input() template='card-01'; @Input() model:UiCardModel={title:''}; @Output() action=new EventEmitter<string>(); }

@Component({selector:'qai-ui-list-card',standalone:true,imports:[CommonModule],template:`
<article class="card" [attr.data-template]="template"><header><div><span class="eyebrow" *ngIf="eyebrow">{{eyebrow}}</span><h3>{{title}}</h3></div><button *ngIf="action" type="button" (click)="actionClick.emit(action?.route||'')">{{action?.label}} →</button></header><div class="list"><div class="item" *ngFor="let item of items"><span class="icon">{{item.icon||'•'}}</span><div class="copy"><strong>{{item.title}}</strong><span>{{item.subtitle}}</span></div><em *ngIf="item.badge" [class.success]="item.tone==='success'">{{item.badge}}</em></div></div></article>`,
styles:[`:host{display:block;min-width:0}.ui-section{display:grid;gap:var(--wl-section-gap,14px);margin:0 0 var(--wl-section-margin,14px)}.columns-1{grid-template-columns:1fr}.columns-2{grid-template-columns:minmax(0,1.35fr) minmax(0,.65fr)}.columns-3{grid-template-columns:repeat(3,minmax(0,1fr))}.columns-4{grid-template-columns:repeat(4,minmax(0,1fr))}.columns-5{grid-template-columns:repeat(5,minmax(0,1fr))}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:var(--wl-kpi-gap,12px);margin-bottom:var(--wl-section-margin,14px)}.steps{display:grid;grid-template-columns:1fr 42px 1fr 42px 1fr 42px 1fr 42px 1fr;align-items:start;padding:var(--wl-steps-padding,18px)}.step{display:flex;gap:10px;min-width:0}.connector{height:1px;margin:15px 8px 0}.card{display:flex;flex-direction:column;min-width:0;height:100%;overflow:hidden}.card .body,.card .list,.card .table-wrap{display:grid;gap:var(--wl-card-gap,12px);min-width:0}.row,.item{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0}.copy{min-width:0;flex:1}.table-wrap{overflow:auto}table{width:100%;border-collapse:separate;border-spacing:0}.metric{position:relative;display:block;width:100%;min-width:0;box-sizing:border-box;text-align:left}.metric:before{content:'';position:absolute;inset:0 0 auto;height:3px}.top{display:flex;align-items:center;gap:9px}.icon{display:grid;place-items:center;flex:0 0 auto}@media(max-width:1100px){.columns-5,.columns-4,.columns-3{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.steps{grid-template-columns:repeat(5,1fr);gap:8px}.connector{display:none}}@media(max-width:680px){.ui-section,.metrics,.steps{grid-template-columns:1fr!important}}`]})
export class UiListCard { @Input() template='list-01'; @Input() eyebrow=''; @Input() title=''; @Input() items:Array<{icon?:string,title:string,subtitle:string,badge?:string,tone?:string}>=[]; @Input() action:UiAction|null=null; @Output() actionClick=new EventEmitter<string>(); }

@Component({selector:'qai-ui-table-card',standalone:true,imports:[CommonModule],template:`
<article class="card" [attr.data-template]="template"><header><div><span class="eyebrow" *ngIf="eyebrow">{{eyebrow}}</span><h3>{{title}}</h3></div><button *ngIf="action" type="button" (click)="actionClick.emit(action?.route||'')">{{action?.label}} →</button></header><div class="table-wrap"><table><thead><tr><th *ngFor="let col of columns">{{col.label}}</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let col of columns">{{row[col.key]}}</td></tr></tbody></table><p *ngIf="!rows.length" class="empty">{{emptyText}}</p></div></article>`,
styles:[`:host{display:block;min-width:0}.ui-section{display:grid;gap:var(--wl-section-gap,14px);margin:0 0 var(--wl-section-margin,14px)}.columns-1{grid-template-columns:1fr}.columns-2{grid-template-columns:minmax(0,1.35fr) minmax(0,.65fr)}.columns-3{grid-template-columns:repeat(3,minmax(0,1fr))}.columns-4{grid-template-columns:repeat(4,minmax(0,1fr))}.columns-5{grid-template-columns:repeat(5,minmax(0,1fr))}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:var(--wl-kpi-gap,12px);margin-bottom:var(--wl-section-margin,14px)}.steps{display:grid;grid-template-columns:1fr 42px 1fr 42px 1fr 42px 1fr 42px 1fr;align-items:start;padding:var(--wl-steps-padding,18px)}.step{display:flex;gap:10px;min-width:0}.connector{height:1px;margin:15px 8px 0}.card{display:flex;flex-direction:column;min-width:0;height:100%;overflow:hidden}.card .body,.card .list,.card .table-wrap{display:grid;gap:var(--wl-card-gap,12px);min-width:0}.row,.item{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0}.copy{min-width:0;flex:1}.table-wrap{overflow:auto}table{width:100%;border-collapse:separate;border-spacing:0}.metric{position:relative;display:block;width:100%;min-width:0;box-sizing:border-box;text-align:left}.metric:before{content:'';position:absolute;inset:0 0 auto;height:3px}.top{display:flex;align-items:center;gap:9px}.icon{display:grid;place-items:center;flex:0 0 auto}@media(max-width:1100px){.columns-5,.columns-4,.columns-3{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.steps{grid-template-columns:repeat(5,1fr);gap:8px}.connector{display:none}}@media(max-width:680px){.ui-section,.metrics,.steps{grid-template-columns:1fr!important}}`]})
export class UiTableCard { @Input() template='table-01'; @Input() eyebrow=''; @Input() title=''; @Input() columns:Array<{key:string,label:string}>=[]; @Input() rows:Array<Record<string,unknown>>=[]; @Input() emptyText='No records.'; @Input() action:UiAction|null=null; @Output() actionClick=new EventEmitter<string>(); }
