import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

export type UiColumns = 1 | 2 | 3 | 4 | 5;
export interface UiAction { label: string; route?: string; }
export interface UiStep { number: string; category: string; title: string; subtitle: string; active?: boolean; }
export interface UiMetric { label: string; value: string | number; subtitle?: string; icon?: string; tone?: 'blue'|'violet'|'green'|'amber'|'rose'; action?: UiAction; }
export interface UiRow { label: string; detail?: string; value: string | number; }
export interface UiCardModel { eyebrow?: string; title: string; subtitle?: string; badge?: string; badgeTone?: 'neutral'|'success'|'info'|'warning'; rows?: UiRow[]; text?: string; action?: UiAction; }

@Component({selector:'qai-ui-section',standalone:true,imports:[CommonModule],template:`<section class="ui-section" [ngClass]="'columns-'+columns"><ng-content/></section>`,styles:[`
:host{display:block;min-width:0}.ui-section{display:grid;gap:14px;margin:0 0 14px}.columns-1{grid-template-columns:1fr}.columns-2{grid-template-columns:minmax(0,1.35fr) minmax(0,.65fr)}.columns-3{grid-template-columns:repeat(3,minmax(0,1fr))}.columns-4{grid-template-columns:repeat(4,minmax(0,1fr))}.columns-5{grid-template-columns:repeat(5,minmax(0,1fr))}@media(max-width:1100px){.columns-5,.columns-4,.columns-3{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.ui-section{grid-template-columns:1fr!important}}
`]})
export class UiSection { @Input() columns:UiColumns=1; }

@Component({selector:'qai-ui-steps',standalone:true,imports:[CommonModule],template:`
<article class="surface"><header><div><span class="eyebrow">{{eyebrow}}</span><h2>{{title}}</h2><p *ngIf="subtitle">{{subtitle}}</p></div><span class="badge" *ngIf="badge"><i></i>{{badge}}</span></header><div class="steps"><ng-container *ngFor="let step of steps;let last=last"><div class="step" [class.active]="step.active"><span class="node">{{step.number}}</span><div><small>{{step.category}}</small><strong>{{step.title}}</strong><em>{{step.subtitle}}</em></div></div><span class="connector" *ngIf="!last"></span></ng-container></div></article>`,
styles:[`:host{display:block}.surface{border:1px solid var(--wl-card-border,var(--wl-border));border-radius:var(--wl-card-radius,12px);background:var(--wl-card-bg,var(--wl-surface));box-shadow:var(--wl-card-shadow,0 4px 14px rgba(15,47,104,.05));overflow:hidden}header{min-height:64px;padding:14px 18px;border-bottom:1px solid var(--wl-card-border,var(--wl-border));background:var(--wl-card-header-bg,var(--wl-surface));display:flex;align-items:center;justify-content:space-between;gap:18px}.eyebrow{display:block;color:var(--wl-card-muted,var(--wl-muted));font-size:9px;font-weight:800;letter-spacing:.9px}h2{margin:5px 0 0;color:var(--wl-card-title,var(--wl-text));font-size:16px}p{margin:4px 0 0;color:var(--wl-card-muted,var(--wl-muted));font-size:10px}.badge{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid var(--wl-badge-border,var(--wl-accent-border));border-radius:var(--wl-badge-radius,999px);background:var(--wl-badge-bg,var(--wl-accent-soft));color:var(--wl-badge-text,var(--wl-accent));font-size:9px;font-weight:700}.badge i{width:6px;height:6px;border-radius:50%;background:#16a34a}.steps{display:grid;grid-template-columns:1fr 42px 1fr 42px 1fr 42px 1fr 42px 1fr;align-items:start;padding:18px}.step{display:flex;gap:10px;min-width:0}.node{display:grid;place-items:center;flex:0 0 30px;width:30px;height:30px;border:1px solid var(--wl-steps-border,var(--wl-border));border-radius:50%;background:var(--wl-steps-bg,var(--wl-surface));color:var(--wl-steps-muted,var(--wl-muted));font-size:8px;font-weight:800}.step.active .node{border-color:var(--wl-accent,#2563eb);background:var(--wl-accent,#2563eb);color:var(--wl-surface,#fff);box-shadow:0 0 0 4px var(--wl-steps-accent-soft,var(--wl-accent-soft))}.step small{display:block;margin:1px 0 4px;color:var(--wl-steps-muted,var(--wl-muted));font-size:8px;font-weight:800;letter-spacing:.8px}.step strong{display:block;color:var(--wl-steps-text,var(--wl-text));font-size:10px}.step em{display:block;margin-top:4px;color:#8793a5;font-size:8px;font-style:normal}.connector{height:1px;margin:15px 8px 0;background:var(--wl-steps-border,var(--wl-border))}@media(max-width:900px){.steps{grid-template-columns:repeat(5,1fr);gap:8px}.connector{display:none}.step{padding:9px;border:1px solid #e1e7ef;border-radius:10px;background:var(--wl-surface-muted,#f8fafc)}}@media(max-width:680px){.steps{grid-template-columns:1fr}}
`]})
export class UiSteps { @Input() eyebrow='WORKFLOW'; @Input() title=''; @Input() subtitle=''; @Input() badge=''; @Input() steps:UiStep[]=[]; }

@Component({selector:'qai-ui-metrics',standalone:true,imports:[CommonModule],template:`<div class="metrics"><button type="button" *ngFor="let item of items; let i = index" class="metric" (click)="action.emit(item.action?.route||'')"><span class="top"><span class="icon">{{item.icon||'•'}}</span><span>{{item.label}}</span></span><strong>{{item.value}}</strong><small>{{item.subtitle}}<i *ngIf="item.action">→</i></small></button></div>`,styles:[`:host{display:block}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-bottom:14px}.metric{--accent:var(--wl-kpi-1,var(--wl-accent,#2563eb));--soft:var(--wl-kpi-header,var(--wl-accent-soft,#edf4ff));position:relative;display:block;width:100%;min-width:0;min-height:126px;padding:16px;text-align:left;border:1px solid var(--wl-kpi-border,var(--wl-border,#d6e0ec));border-radius:var(--wl-kpi-radius,12px);background:var(--wl-kpi-bg,var(--wl-surface,#fff));box-shadow:0 4px 14px rgba(15,47,104,.05);cursor:pointer;box-sizing:border-box}.metric:before{content:'';position:absolute;inset:0 0 auto;height:3px;background:var(--accent);border-radius:var(--wl-kpi-radius,12px) var(--wl-kpi-radius,12px) 0 0}.top{display:flex;align-items:center;gap:9px;color:var(--wl-kpi-text,var(--wl-text,#26364d));font-size:11px;font-weight:700}.icon{width:31px;height:31px;display:grid;place-items:center;border-radius:9px;background:var(--soft);color:var(--accent);font-size:11px}.metric>strong{display:block;margin:15px 0 13px;color:var(--wl-kpi-title,var(--wl-text,#141c2d));font-size:28px;line-height:1}.metric small{display:flex;align-items:center;color:var(--wl-kpi-muted,var(--wl-muted,#7b8798));font-size:9px}.metric small i{margin-left:auto;color:var(--accent);font-size:13px;font-style:normal}@media(max-width:1180px){.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:680px){.metrics{grid-template-columns:1fr}}
`]})
export class UiMetrics {
  @Input() items:UiMetric[]=[];
  @Output() action=new EventEmitter<string>();
}

@Component({selector:'qai-ui-card',standalone:true,imports:[CommonModule],template:`
<article class="card"><header><div><span class="eyebrow" *ngIf="model.eyebrow">{{model.eyebrow}}</span><h3>{{model.title}}</h3><p *ngIf="model.subtitle">{{model.subtitle}}</p></div><span class="status" *ngIf="model.badge" [class.success]="model.badgeTone==='success'">{{model.badge}}</span></header><div class="body"><div class="row" *ngFor="let row of model.rows;let first=first" [class.first]="first"><span><small>{{row.label}}</small><em *ngIf="row.detail">{{row.detail}}</em></span><strong>{{row.value}}</strong></div><p class="text" *ngIf="model.text">{{model.text}}</p></div><footer *ngIf="model.action"><span>Next action</span><button type="button" (click)="action.emit(model.action?.route||'')">{{model.action?.label}} →</button></footer><ng-content/></article>`,
styles:[`:host{display:block;min-width:0}.card{display:flex;flex-direction:column;min-height:var(--ui-height, 100%);border:1px solid var(--wl-card-border,var(--wl-border));border-radius:var(--wl-card-radius,12px);background:var(--wl-card-bg,var(--wl-surface));box-shadow:var(--wl-card-shadow,0 4px 14px rgba(15,47,104,.05));overflow:hidden}header{min-height:64px;padding:14px 18px;border-bottom:1px solid var(--wl-card-border,var(--wl-border));background:var(--wl-card-header-bg,var(--wl-surface));display:flex;align-items:center;justify-content:space-between;gap:14px}.eyebrow{display:block;color:var(--wl-card-muted,var(--wl-muted));font-size:9px;font-weight:800;letter-spacing:.9px}h3{margin:5px 0 0;color:var(--wl-card-title,var(--wl-text));font-size:14px}header p{margin:4px 0 0;color:var(--wl-card-muted,var(--wl-muted));font-size:9px}.status{padding:5px 8px;border:1px solid #cfe0fa;border-radius:999px;background:#edf4ff;color:#1558ad;font-size:8px;font-weight:800}.status.success{border-color:var(--wl-badge-border,var(--wl-accent-border));background:var(--wl-badge-bg,var(--wl-accent-soft));color:var(--wl-badge-text,var(--wl-accent))}.body{display:grid;gap:9px;padding:14px 17px 9px;flex:1;background:var(--wl-card-bg,var(--wl-surface-muted))}.row{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:58px;padding:10px 12px;border:1px solid var(--wl-card-border,var(--wl-border));border-radius:10px;background:var(--wl-card-bg,var(--wl-surface))}.row.first{border-color:var(--wl-accent-border,var(--wl-border));background:var(--wl-accent-soft,var(--wl-surface))}.row small{display:block;color:var(--wl-card-muted,var(--wl-muted));font-size:10px;font-weight:600}.row em{display:block;margin-top:3px;color:var(--wl-card-muted,var(--wl-muted));font-size:8px;font-style:normal}.row strong{color:var(--wl-card-text,var(--wl-text));font-size:17px}.row.first strong{color:var(--wl-card-title,var(--wl-text));font-size:20px}.text{margin:0;padding:4px 2px 10px;color:var(--wl-card-text,var(--wl-text));font-size:11px;line-height:1.7}footer{display:grid;grid-template-columns:1fr auto;margin:0 17px 17px;padding:10px 12px;border:1px solid var(--wl-card-border,var(--wl-border));border-radius:9px;background:var(--wl-surface-muted,var(--wl-card-bg));color:var(--wl-card-text,var(--wl-text));font-size:9px}footer button{padding:0;border:0;background:transparent;color:var(--wl-card-accent,var(--wl-accent));font-size:9px;font-weight:700;cursor:pointer}
`]})
export class UiCard { @Input() model:UiCardModel={title:''}; @Output() action=new EventEmitter<string>(); }

@Component({selector:'qai-ui-list-card',standalone:true,imports:[CommonModule],template:`
<article class="card"><header><div><span class="eyebrow" *ngIf="eyebrow">{{eyebrow}}</span><h3>{{title}}</h3></div><button *ngIf="action" type="button" (click)="actionClick.emit(action?.route||'')">{{action?.label}} →</button></header><div class="list"><div class="item" *ngFor="let item of items"><span class="icon">{{item.icon||'•'}}</span><div class="copy"><strong>{{item.title}}</strong><span>{{item.subtitle}}</span></div><em *ngIf="item.badge" [class.success]="item.tone==='success'">{{item.badge}}</em></div></div></article>`,
styles:[`:host{display:block;min-width:0}.card{height:100%;border:1px solid var(--wl-card-border,var(--wl-border));border-radius:var(--wl-card-radius,12px);background:var(--wl-card-bg,var(--wl-surface));box-shadow:var(--wl-card-shadow,0 4px 14px rgba(15,47,104,.05));overflow:hidden}header{min-height:64px;padding:14px 18px;border-bottom:1px solid var(--wl-card-border,var(--wl-border));background:var(--wl-card-header-bg,var(--wl-surface));display:flex;align-items:center;justify-content:space-between;gap:14px}.eyebrow{display:block;color:var(--wl-card-muted,var(--wl-muted));font-size:9px;font-weight:800;letter-spacing:.9px}h3{margin:5px 0 0;color:var(--wl-card-title,var(--wl-text));font-size:14px}header button{padding:7px 9px;border:1px solid var(--wl-button-2-border,var(--wl-border));border-radius:8px;background:var(--wl-card-bg,var(--wl-surface));color:var(--wl-button-2-text,var(--wl-text));font-size:9px;font-weight:700}.list{display:grid;gap:9px;padding:14px 17px 17px;background:var(--wl-surface-muted,#f8fafc)}.item{display:flex;align-items:center;gap:10px;min-height:61px;padding:10px 12px;border:1px solid var(--wl-card-border,var(--wl-border));border-radius:10px;background:var(--wl-card-bg,var(--wl-surface))}.icon{width:32px;height:32px;display:grid;place-items:center;flex:0 0 auto;border:1px solid var(--wl-list-border,var(--wl-border));border-radius:50%;background:var(--wl-accent-soft,var(--wl-surface-muted));color:var(--wl-list-accent,var(--wl-accent));font-size:11px}.copy{min-width:0;flex:1}.copy strong{display:block;color:var(--wl-card-text,var(--wl-text));font-size:10px}.copy span{display:block;margin-top:3px;color:var(--wl-list-muted,var(--wl-muted));font-size:8px;line-height:1.4}.item em{padding:4px 7px;border:1px solid #cfe0fa;border-radius:999px;background:var(--wl-badge-bg,var(--wl-accent-soft));color:var(--wl-badge-text,var(--wl-accent));font-size:7px;font-style:normal;font-weight:800}.item em.success{border-color:var(--wl-badge-border,var(--wl-accent-border));background:var(--wl-badge-bg,var(--wl-accent-soft));color:var(--wl-badge-text,var(--wl-accent))}
`]})
export class UiListCard { @Input() eyebrow=''; @Input() title=''; @Input() items:Array<{icon?:string,title:string,subtitle:string,badge?:string,tone?:string}>=[]; @Input() action:UiAction|null=null; @Output() actionClick=new EventEmitter<string>(); }

@Component({selector:'qai-ui-table-card',standalone:true,imports:[CommonModule],template:`
<article class="card"><header><div><span class="eyebrow" *ngIf="eyebrow">{{eyebrow}}</span><h3>{{title}}</h3></div><button *ngIf="action" type="button" (click)="actionClick.emit(action?.route||'')">{{action?.label}} →</button></header><div class="table-wrap"><table><thead><tr><th *ngFor="let col of columns">{{col.label}}</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let col of columns">{{row[col.key]}}</td></tr></tbody></table><p *ngIf="!rows.length" class="empty">{{emptyText}}</p></div></article>`,
styles:[`:host{display:block;min-width:0}.card{height:100%;border:1px solid var(--wl-card-border,var(--wl-border));border-radius:var(--wl-card-radius,12px);background:var(--wl-card-bg,var(--wl-surface));box-shadow:var(--wl-card-shadow,0 4px 14px rgba(15,47,104,.05));overflow:hidden}header{min-height:64px;padding:14px 18px;border-bottom:1px solid var(--wl-card-border,var(--wl-border));background:var(--wl-card-header-bg,var(--wl-surface));display:flex;align-items:center;justify-content:space-between;gap:14px}.eyebrow{display:block;color:var(--wl-card-muted,var(--wl-muted));font-size:9px;font-weight:800;letter-spacing:.9px}h3{margin:5px 0 0;color:var(--wl-card-title,var(--wl-text));font-size:14px}header button{padding:7px 9px;border:1px solid var(--wl-button-2-border,var(--wl-border));border-radius:8px;background:var(--wl-card-bg,var(--wl-surface));color:var(--wl-button-2-text,var(--wl-text));font-size:9px;font-weight:700}.table-wrap{overflow:auto;padding:14px 17px 17px;background:var(--wl-surface-muted,#f8fafc)}table{width:100%;border-collapse:separate;border-spacing:0;font-size:9px}th{padding:9px 10px;text-align:left;border:1px solid var(--wl-table-border,var(--wl-border));background:var(--wl-table-header,var(--wl-surface-muted));color:var(--wl-table-muted,var(--wl-muted));font-size:8px;font-weight:800;text-transform:uppercase}td{padding:11px 10px;border-bottom:1px solid var(--wl-table-border,var(--wl-border));background:var(--wl-card-bg,var(--wl-surface));color:var(--wl-table-text,var(--wl-text))}.empty{margin:14px 2px;color:var(--wl-list-muted,var(--wl-muted));font-size:10px}
`]})
export class UiTableCard { @Input() eyebrow=''; @Input() title=''; @Input() columns:Array<{key:string,label:string}>=[]; @Input() rows:Array<Record<string,unknown>>=[]; @Input() emptyText='No records.'; @Input() action:UiAction|null=null; @Output() actionClick=new EventEmitter<string>(); }
