import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

export type UiColumns = 1 | 2 | 3 | 4 | 5;
export interface UiAction { label: string; route?: string; }
export interface UiStep { number: string; category: string; title: string; subtitle: string; active?: boolean; }
export interface UiMetric { label: string; value: string | number; subtitle?: string; icon?: string; tone?: 'blue'|'violet'|'green'|'amber'|'rose'; action?: UiAction; }
export interface UiRow { label: string; detail?: string; value: string | number; }
export interface UiCardModel { eyebrow?: string; title: string; subtitle?: string; badge?: string; badgeTone?: 'neutral'|'success'|'info'|'warning'; rows?: UiRow[]; text?: string; action?: UiAction; }

@Component({selector:'qai-ui-section',standalone:true,imports:[CommonModule],template:`<section class="ui-section" [ngClass]="'columns-'+columns"><ng-content/></section>`,styles:[`
:host{display:block;min-width:0}.ui-section{display:grid;gap:14px;margin:0 0 14px}.columns-1{grid-template-columns:1fr}.columns-2{grid-template-columns:minmax(0,1.35fr) minmax(0,.65fr)}.columns-3{grid-template-columns:repeat(3,minmax(0,1fr))}.columns-4{grid-template-columns:repeat(4,minmax(0,1fr))}.columns-5{grid-template-columns:repeat(5,minmax(0,1fr))}@media(max-width:1100px){.columns-5,.columns-4,.columns-3{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.ui-section{grid-template-columns:1fr!important}}
`]})
export class UiSection { @Input() columns:UiColumns=1; }

@Component({selector:'qai-ui-steps',standalone:true,imports:[CommonModule],template:`
<article class="surface"><header><div><span class="eyebrow">{{eyebrow}}</span><h2>{{title}}</h2><p *ngIf="subtitle">{{subtitle}}</p></div><span class="badge" *ngIf="badge"><i></i>{{badge}}</span></header><div class="steps"><ng-container *ngFor="let step of steps;let last=last"><div class="step" [class.active]="step.active"><span class="node">{{step.number}}</span><div><small>{{step.category}}</small><strong>{{step.title}}</strong><em>{{step.subtitle}}</em></div></div><span class="connector" *ngIf="!last"></span></ng-container></div></article>`,
styles:[`:host{display:block}.surface{border:1px solid #d6e0ec;border-radius:14px;background:#fff;box-shadow:0 7px 20px rgba(15,47,104,.055);overflow:hidden}header{min-height:64px;padding:14px 18px;border-bottom:1px solid #bfd3ef;background:#d6e8ff;display:flex;align-items:center;justify-content:space-between;gap:18px}.eyebrow{display:block;color:#68778d;font-size:9px;font-weight:800;letter-spacing:.9px}h2{margin:5px 0 0;color:#173f7a;font-size:16px}p{margin:4px 0 0;color:#68778d;font-size:10px}.badge{display:inline-flex;align-items:center;gap:7px;padding:7px 10px;border:1px solid #dce5f1;border-radius:999px;background:#f7faff;color:#64748b;font-size:9px;font-weight:700}.badge i{width:6px;height:6px;border-radius:50%;background:#16a34a}.steps{display:grid;grid-template-columns:1fr 42px 1fr 42px 1fr 42px 1fr 42px 1fr;align-items:start;padding:18px}.step{display:flex;gap:10px;min-width:0}.node{display:grid;place-items:center;flex:0 0 30px;width:30px;height:30px;border:1px solid #cbd8e8;border-radius:50%;background:#f4f7fb;color:#64748b;font-size:8px;font-weight:800}.step.active .node{border-color:#2563eb;background:#2563eb;color:#fff;box-shadow:0 0 0 4px #dbeafe}.step small{display:block;margin:1px 0 4px;color:#8290a4;font-size:8px;font-weight:800;letter-spacing:.8px}.step strong{display:block;color:#1f2937;font-size:10px}.step em{display:block;margin-top:4px;color:#8793a5;font-size:8px;font-style:normal}.connector{height:1px;margin:15px 8px 0;background:#cbd7e6}@media(max-width:900px){.steps{grid-template-columns:repeat(5,1fr);gap:8px}.connector{display:none}.step{padding:9px;border:1px solid #e1e7ef;border-radius:10px;background:#f8fafc}}@media(max-width:680px){.steps{grid-template-columns:1fr}}
`]})
export class UiSteps { @Input() eyebrow='WORKFLOW'; @Input() title=''; @Input() subtitle=''; @Input() badge=''; @Input() steps:UiStep[]=[]; }

@Component({selector:'qai-ui-metrics',standalone:true,imports:[CommonModule],template:`<div class="metrics"><button type="button" *ngFor="let item of items" [class]="'metric '+(item.tone||'blue')" (click)="action.emit(item.action?.route||'')"><span class="top"><span class="icon">{{item.icon||'•'}}</span><span>{{item.label}}</span></span><strong>{{item.value}}</strong><small>{{item.subtitle}}<i *ngIf="item.action">→</i></small></button></div>`,styles:[`:host{display:block}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-bottom:14px}.metric{--accent:#2563eb;--soft:#e8f0ff;position:relative;display:block;min-height:126px;padding:16px;text-align:left;border:1px solid #d6e0ec;border-radius:13px;background:#fff;box-shadow:0 7px 20px rgba(15,47,104,.055);cursor:pointer}.metric:before{content:'';position:absolute;inset:0 0 auto;height:3px;background:var(--accent)}.metric.violet{--accent:#7c3aed;--soft:#eee9fe}.metric.green{--accent:#059669;--soft:#dcf8e9}.metric.amber{--accent:#d97706;--soft:#fef3c7}.metric.rose{--accent:#e11d48;--soft:#ffe4e6}.top{display:flex;align-items:center;gap:9px;color:#5f6c80;font-size:11px;font-weight:700}.icon{width:31px;height:31px;display:grid;place-items:center;border-radius:9px;background:var(--soft);color:var(--accent);font-size:11px}.metric>strong{display:block;margin:15px 0 13px;color:#141c2d;font-size:28px;line-height:1}.metric small{display:flex;align-items:center;color:#7b8798;font-size:9px}.metric small i{margin-left:auto;color:var(--accent);font-size:13px;font-style:normal}@media(max-width:1180px){.metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:680px){.metrics{grid-template-columns:1fr}}
`]})
export class UiMetrics { @Input() items:UiMetric[]=[]; @Output() action=new EventEmitter<string>(); }

@Component({selector:'qai-ui-card',standalone:true,imports:[CommonModule],template:`
<article class="card"><header><div><span class="eyebrow" *ngIf="model.eyebrow">{{model.eyebrow}}</span><h3>{{model.title}}</h3><p *ngIf="model.subtitle">{{model.subtitle}}</p></div><span class="status" *ngIf="model.badge" [class.success]="model.badgeTone==='success'">{{model.badge}}</span></header><div class="body"><div class="row" *ngFor="let row of model.rows;let first=first" [class.first]="first"><span><small>{{row.label}}</small><em *ngIf="row.detail">{{row.detail}}</em></span><strong>{{row.value}}</strong></div><p class="text" *ngIf="model.text">{{model.text}}</p></div><footer *ngIf="model.action"><span>Next action</span><button type="button" (click)="action.emit(model.action?.route||'')">{{model.action?.label}} →</button></footer><ng-content/></article>`,
styles:[`:host{display:block;min-width:0}.card{display:flex;flex-direction:column;min-height:var(--ui-height, 100%);border:1px solid var(--ui-border,#d6e0ec);border-radius:var(--ui-radius,14px);background:var(--ui-surface,#fff);box-shadow:0 7px 20px rgba(15,47,104,.055);overflow:hidden}header{min-height:64px;padding:14px 18px;border-bottom:1px solid var(--ui-border,#bfd3ef);background:var(--ui-header,#d6e8ff);display:flex;align-items:center;justify-content:space-between;gap:14px}.eyebrow{display:block;color:var(--ui-muted,#68778d);font-size:9px;font-weight:800;letter-spacing:.9px}h3{margin:5px 0 0;color:var(--ui-title,#173f7a);font-size:14px}header p{margin:4px 0 0;color:var(--ui-muted,#68778d);font-size:9px}.status{padding:5px 8px;border:1px solid #cfe0fa;border-radius:999px;background:#edf4ff;color:#1558ad;font-size:8px;font-weight:800}.status.success{border-color:#bce8cf;background:#edf9f2;color:#167344}.body{display:grid;gap:9px;padding:14px 17px 9px;flex:1;background:var(--ui-surface,#f8fafc)}.row{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:58px;padding:10px 12px;border:1px solid #d4dfec;border-radius:10px;background:var(--ui-surface,#fff)}.row.first{border-color:#bfd3ef;background:#edf4ff}.row small{display:block;color:var(--ui-muted,#68778d);font-size:10px;font-weight:600}.row em{display:block;margin-top:3px;color:#8b98aa;font-size:8px;font-style:normal}.row strong{color:var(--ui-text,#26364d);font-size:17px}.row.first strong{color:var(--ui-title,#173f7a);font-size:20px}.text{margin:0;padding:4px 2px 10px;color:var(--ui-text,#66748a);font-size:11px;line-height:1.7}footer{display:grid;grid-template-columns:1fr auto;margin:0 17px 17px;padding:10px 12px;border:1px solid #d4dfec;border-radius:9px;background:#f4f7fb;color:var(--ui-text,#66748a);font-size:9px}footer button{padding:0;border:0;background:transparent;color:var(--ui-accent,#315fbd);font-size:9px;font-weight:700;cursor:pointer}
`]})
export class UiCard { @Input() model:UiCardModel={title:''}; @Output() action=new EventEmitter<string>(); }

@Component({selector:'qai-ui-list-card',standalone:true,imports:[CommonModule],template:`
<article class="card"><header><div><span class="eyebrow" *ngIf="eyebrow">{{eyebrow}}</span><h3>{{title}}</h3></div><button *ngIf="action" type="button" (click)="actionClick.emit(action?.route||'')">{{action?.label}} →</button></header><div class="list"><div class="item" *ngFor="let item of items"><span class="icon">{{item.icon||'•'}}</span><div class="copy"><strong>{{item.title}}</strong><span>{{item.subtitle}}</span></div><em *ngIf="item.badge" [class.success]="item.tone==='success'">{{item.badge}}</em></div></div></article>`,
styles:[`:host{display:block;min-width:0}.card{height:100%;border:1px solid #d6e0ec;border-radius:14px;background:#fff;box-shadow:0 7px 20px rgba(15,47,104,.055);overflow:hidden}header{min-height:64px;padding:14px 18px;border-bottom:1px solid #bfd3ef;background:#d6e8ff;display:flex;align-items:center;justify-content:space-between;gap:14px}.eyebrow{display:block;color:#68778d;font-size:9px;font-weight:800;letter-spacing:.9px}h3{margin:5px 0 0;color:#173f7a;font-size:14px}header button{padding:7px 9px;border:1px solid #b9cff0;border-radius:8px;background:#fff;color:#245bb5;font-size:9px;font-weight:700}.list{display:grid;gap:9px;padding:14px 17px 17px;background:#f8fafc}.item{display:flex;align-items:center;gap:10px;min-height:61px;padding:10px 12px;border:1px solid #d4dfec;border-radius:10px;background:#fff}.icon{width:32px;height:32px;display:grid;place-items:center;flex:0 0 auto;border:1px solid #cbdcf9;border-radius:50%;background:#e8f0ff;color:#315fbd;font-size:11px}.copy{min-width:0;flex:1}.copy strong{display:block;color:#26364d;font-size:10px}.copy span{display:block;margin-top:3px;color:#7b8798;font-size:8px;line-height:1.4}.item em{padding:4px 7px;border:1px solid #cfe0fa;border-radius:999px;background:#edf4ff;color:#315fbd;font-size:7px;font-style:normal;font-weight:800}.item em.success{border-color:#bce8cf;background:#edf9f2;color:#167344}
`]})
export class UiListCard { @Input() eyebrow=''; @Input() title=''; @Input() items:Array<{icon?:string,title:string,subtitle:string,badge?:string,tone?:string}>=[]; @Input() action:UiAction|null=null; @Output() actionClick=new EventEmitter<string>(); }

@Component({selector:'qai-ui-table-card',standalone:true,imports:[CommonModule],template:`
<article class="card"><header><div><span class="eyebrow" *ngIf="eyebrow">{{eyebrow}}</span><h3>{{title}}</h3></div><button *ngIf="action" type="button" (click)="actionClick.emit(action?.route||'')">{{action?.label}} →</button></header><div class="table-wrap"><table><thead><tr><th *ngFor="let col of columns">{{col.label}}</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let col of columns">{{row[col.key]}}</td></tr></tbody></table><p *ngIf="!rows.length" class="empty">{{emptyText}}</p></div></article>`,
styles:[`:host{display:block;min-width:0}.card{height:100%;border:1px solid #d6e0ec;border-radius:14px;background:#fff;box-shadow:0 7px 20px rgba(15,47,104,.055);overflow:hidden}header{min-height:64px;padding:14px 18px;border-bottom:1px solid #bfd3ef;background:#d6e8ff;display:flex;align-items:center;justify-content:space-between;gap:14px}.eyebrow{display:block;color:#68778d;font-size:9px;font-weight:800;letter-spacing:.9px}h3{margin:5px 0 0;color:#173f7a;font-size:14px}header button{padding:7px 9px;border:1px solid #b9cff0;border-radius:8px;background:#fff;color:#245bb5;font-size:9px;font-weight:700}.table-wrap{overflow:auto;padding:14px 17px 17px;background:#f8fafc}table{width:100%;border-collapse:separate;border-spacing:0;font-size:9px}th{padding:9px 10px;text-align:left;border:1px solid #d4dce7;background:#e8eef6;color:#69768a;font-size:8px;font-weight:800;text-transform:uppercase}td{padding:11px 10px;border-bottom:1px solid #d9e0e9;background:#fff;color:#5f6c80}.empty{margin:14px 2px;color:#7b8798;font-size:10px}
`]})
export class UiTableCard { @Input() eyebrow=''; @Input() title=''; @Input() columns:Array<{key:string,label:string}>=[]; @Input() rows:Array<Record<string,unknown>>=[]; @Input() emptyText='No records.'; @Input() action:UiAction|null=null; @Output() actionClick=new EventEmitter<string>(); }
