import { CommonModule } from '@angular/common';
import { Component,OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin,Observable,of,switchMap } from 'rxjs';
import { AuthService } from '../../core/auth.service';
import { PageHeader } from '../../shared/ui';
import { LicenseCatalog,ModuleAdminService,PlanDefinition,TenantEntitlements,TenantSummary } from './module-admin.service';

@Component({standalone:true,imports:[CommonModule,FormsModule,PageHeader],styles:[`
.master{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:end}.master label,.admin-form label,.create-form label{display:flex;flex-direction:column;gap:6px;font-size:9px;font-weight:700}.master select,.admin-form input,.admin-form select,.create-form input{height:38px;border:1px solid var(--line);border-radius:8px;padding:0 10px}.create-form label small{color:var(--muted);font-size:8px;font-weight:500;line-height:1.4}.tenant-meta{display:flex;gap:8px;align-items:center;font-size:8px;color:var(--muted);margin-top:7px}.module-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.module-card{display:grid;grid-template-columns:38px 1fr auto;gap:10px;align-items:center;border:1px solid var(--line);border-radius:10px;padding:13px}.module-card.locked{background:#f8fafc}.module-card i{width:36px;height:36px;display:grid;place-items:center;border-radius:8px;background:#eff6ff;color:#2563eb;font-style:normal}.module-card b,.module-card small{display:block}.module-card b{font-size:10px;text-transform:capitalize}.module-card small{font-size:8px;color:var(--muted);margin-top:3px}.admin-form,.create-form{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}.notice{padding:11px;border-radius:8px;font-size:9px;margin-bottom:12px}.notice.ok{background:#ecfdf3;color:#166534}.notice.bad{background:#fef2f2;color:#b91c1c}.plan-note{font-size:8px;color:var(--muted);margin:10px 0 0}.actions{display:flex;gap:7px;flex-wrap:wrap}@media(max-width:1000px){.module-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.module-grid,.admin-form,.create-form,.master{grid-template-columns:1fr}}
`],template:`
<qai-page-header [title]="systemAdmin?'Master Client Administration':'Modules & Features'" subtitle="Control tenant plans, demo access, limits and paid capabilities.">
  <button *ngIf="systemAdmin" (click)="creating=!creating">+ Client</button><button class="primary" (click)="save()" [disabled]="busy||!selectedTenantId">{{busy?'Saving…':license?'Save access':'Assign license'}}</button>
</qai-page-header>
<div *ngIf="message" class="notice" [class.ok]="success" [class.bad]="!success">{{message}}</div>
<section class="panel" *ngIf="systemAdmin"><div class="master"><label>Client / tenant<select [(ngModel)]="selectedTenantId" (ngModelChange)="loadSelected()"><option *ngFor="let t of tenants" [value]="t.id">{{t.name}} — {{t.slug}}</option></select></label><div class="actions"><button (click)="toggleTenant()">{{selectedTenant?.status==='Active'?'Suspend client':'Activate client'}}</button><button (click)="loadPresentationDemo()" [disabled]="busy||selectedPlan!=='demo'">Load presentation demo</button></div></div><div class="tenant-meta" *ngIf="selectedTenant"><span class="pill" [class.success]="selectedTenant.status==='Active'">{{selectedTenant.status}}</span><span>{{selectedTenant.contactEmail}}</span><span>{{selectedTenant.id}}</span></div></section>
<section class="panel form" *ngIf="creating" style="margin-top:13px"><header><b>Create client workspace and administrator</b></header><div class="create-form"><label>Company name<input [(ngModel)]="newTenant.name"></label><label>Slug<input [(ngModel)]="newTenant.slug"></label><label>Admin email<input type="email" [(ngModel)]="newTenant.contactEmail"></label><label>Admin first name<input [(ngModel)]="newTenant.firstName"></label><label>Admin last name<input [(ngModel)]="newTenant.lastName"></label><label>Temporary password<input type="password" minlength="10" autocomplete="new-password" [(ngModel)]="newTenant.password"><small>10+ characters with uppercase, lowercase, number and special character.</small></label></div><button class="primary" [disabled]="busy||!canCreateClient" (click)="createClient()">Create and configure</button></section>
<section class="panel" *ngIf="selectedTenantId" style="margin-top:13px"><header><div><b>Subscription controls</b><span>Changes are enforced by the API and published to platform services.</span></div><span class="pill" [class.success]="license?.isUsable">{{license?.licenseStatus||'Unlicensed'}}</span></header><div class="admin-form"><label>Plan<select [(ngModel)]="selectedPlan" (ngModelChange)="planChanged()"><option *ngFor="let p of catalog?.plans" [value]="p.code">{{p.name}}</option></select></label><label>Maximum users<input type="number" min="1" [(ngModel)]="maxUsers"></label><label>Expires on<input type="date" [(ngModel)]="expiryDate"></label></div><p class="plan-note">{{license?'License version '+license.version:'No license assigned'}} · Demo defaults to 14 days. Settings and Billing remain active to prevent lockout.</p><div class="actions" style="margin-top:10px" *ngIf="license"><button (click)="toggleLicense()">{{license.licenseStatus==='Active'?'Suspend license':'Activate license'}}</button></div></section>
<section class="panel" *ngIf="selectedTenantId" style="margin-top:13px"><header><div><b>Enabled modules</b><span>Only modules included in {{selectedPlan|titlecase}} can be enabled.</span></div><strong>{{enabled.size}} / {{catalog?.modules?.length||0}}</strong></header><div class="module-grid"><article class="module-card" *ngFor="let module of catalog?.modules" [class.locked]="!available(module)"><i>{{icon(module)}}</i><div><b>{{label(module)}}</b><small>{{description(module)}}<ng-container *ngIf="!available(module)"> · Upgrade required</ng-container></small></div><label class="toggle"><input type="checkbox" [checked]="enabled.has(module)" [disabled]="core(module)||!available(module)" (change)="setModule(module,$any($event.target).checked)"><span></span></label></article></div></section>`})
export class ModuleAdminPage implements OnInit{
  catalog?:LicenseCatalog;tenants:TenantSummary[]=[];selectedTenantId='';license?:TenantEntitlements;selectedPlan='demo';maxUsers=5;expiryDate='';enabled=new Set<string>();busy=false;message='';success=false;creating=false;newTenant={name:'',slug:'',contactEmail:'',firstName:'',lastName:'',password:''};
  readonly systemAdmin=this.auth.hasPermission('system.admin');
  private descriptions:Record<string,string>={crm:'Prospects, campaigns, leads and pipeline',inbox:'Customer conversations and replies',ticketing:'Issue tracking and resolution',automation:'Scheduled and event-driven workflows',knowledge:'Business knowledge and guidance',ai:'Advanced business assistants and evaluation',analytics:'Performance, funnel and ROI reporting',integrations:'External systems and provider connections',settings:'Users, access and tenant configuration',billing:'Plan, entitlement and usage controls'};
  constructor(private data:ModuleAdminService,private auth:AuthService){}
  ngOnInit(){if(this.systemAdmin){forkJoin({catalog:this.data.catalog(),tenants:this.data.tenants()}).subscribe({next:r=>{this.catalog=r.catalog;this.tenants=r.tenants;this.selectedTenantId=r.tenants.find(x=>x.id===this.auth.session()?.tenantId)?.id||r.tenants[0]?.id||'';this.loadSelected()},error:e=>this.fail(this.error(e))})}else{this.data.catalog().subscribe({next:c=>{this.catalog=c;this.selectedTenantId=this.auth.session()?.tenantId||'';this.loadSelected()},error:e=>this.fail(this.error(e))})}}
  get selectedTenant(){return this.tenants.find(x=>x.id===this.selectedTenantId)}get plan():PlanDefinition|undefined{return this.catalog?.plans.find(x=>x.code===this.selectedPlan)}
  get canCreateClient(){const n=this.newTenant;return!!n.name.trim()&&!!n.slug.trim()&&!!n.contactEmail.trim()&&!!n.firstName.trim()&&!!n.lastName.trim()&&this.validPassword(n.password)}
  loadSelected(){this.message='';this.license=undefined;if(!this.selectedTenantId)return;this.data.entitlements(this.selectedTenantId).subscribe({next:r=>this.apply(r),error:e=>{if(e.status===404)this.resetDraft();else this.fail(this.error(e))}})}
  planChanged(){const p=this.plan;if(!p)return;this.maxUsers=p.defaultMaxUsers;this.enabled=new Set([...this.enabled].filter(x=>p.modules.includes(x)));if(this.enabled.size<=2)p.modules.forEach(x=>this.enabled.add(x));this.enabled.add('settings');this.enabled.add('billing');if(p.code==='demo'){const d=new Date();d.setUTCDate(d.getUTCDate()+14);this.expiryDate=d.toISOString().slice(0,10)}}
  save(){if(!this.selectedTenantId||!this.plan)return;this.busy=true;this.message='';const expiry=this.expiryDate?new Date(this.expiryDate+'T23:59:59Z').toISOString():null;const common={plan:this.selectedPlan,maxUsers:this.maxUsers,expiresAtUtc:expiry,modules:[...this.enabled]};const call:Observable<unknown>=this.license?this.data.update(this.selectedTenantId,common):this.data.assign(this.selectedTenantId,{...common,startsAtUtc:new Date().toISOString()});call.pipe(switchMap(()=>this.selectedTenantId===this.auth.session()?.tenantId?this.auth.refreshAccessToken():of('')),switchMap(()=>this.data.entitlements(this.selectedTenantId))).subscribe({next:r=>{this.apply(r);this.ok(this.selectedPlan==='demo'?'Demo access configured. Presentation records are loaded only with the explicit Load presentation demo action.':'Client access updated. API enforcement and module navigation now follow this license.')},error:e=>this.fail(this.error(e))})}
  createClient(){const n=this.newTenant;if(!this.canCreateClient)return this.fail('Complete every field and use a 10+ character password with uppercase, lowercase, number and special character.');this.busy=true;this.data.createTenant({name:n.name,slug:n.slug,contactEmail:n.contactEmail}).pipe(switchMap(t=>this.data.createTenantAdmin(t.id,{email:n.contactEmail,password:n.password,firstName:n.firstName,lastName:n.lastName}).pipe(switchMap(()=>of(t))))).subscribe({next:t=>{this.tenants=[...this.tenants,t].sort((a,b)=>a.name.localeCompare(b.name));this.selectedTenantId=t.id;this.creating=false;this.newTenant={name:'',slug:'',contactEmail:'',firstName:'',lastName:'',password:''};this.resetDraft();this.ok('Client and administrator created. Choose a plan and assign its license.')},error:e=>this.fail(this.error(e))})}
  toggleLicense(){if(!this.license)return;this.busy=true;const call=this.license.licenseStatus==='Active'?this.data.suspend(this.selectedTenantId):this.data.activate(this.selectedTenantId);call.pipe(switchMap(()=>this.data.entitlements(this.selectedTenantId))).subscribe({next:r=>{this.apply(r);this.ok(`License is now ${r.licenseStatus.toLowerCase()}.`)},error:e=>this.fail(this.error(e))})}
  toggleTenant(){const t=this.selectedTenant;if(!t)return;this.busy=true;const next=t.status==='Active'?'Suspended':'Active';const call=t.status==='Active'?this.data.suspendTenant(t.id):this.data.activateTenant(t.id);call.subscribe({next:()=>{t.status=next;this.ok(`Client is now ${next.toLowerCase()}.`)},error:e=>this.fail(this.error(e))})}
  loadPresentationDemo(){if(!this.selectedTenantId||!this.license)return this.fail('Assign the demo license before loading a presentation scenario.');if(!confirm('This clears only the selected tenant business records and loads safe [PRESENTATION] .example data. Users, licenses and settings remain. Continue?'))return;this.busy=true;this.data.loadPresentationDemo(this.selectedTenantId).subscribe({next:r=>this.ok(`Presentation demo loaded: ${r.scenario?.prospects||r.prospects||0} prospects, ${r.scenario?.campaigns||r.campaigns||0} campaigns and ${r.scenario?.opportunities||r.opportunities||0} opportunities.`),error:e=>this.fail(this.error(e))})}
  available(m:string){return!!this.plan?.modules.includes(m)}core(m:string){return m==='settings'||m==='billing'}setModule(m:string,on:boolean){on?this.enabled.add(m):this.enabled.delete(m)}label(m:string){return m==='ai'?'Business assistants':m}description(m:string){return this.descriptions[m]||'Product capability'}icon(m:string){return({crm:'◎',inbox:'▱',ticketing:'▣',automation:'⚡',knowledge:'▥',ai:'✦',analytics:'▤',integrations:'↗',settings:'⚙',billing:'€'}as Record<string,string>)[m]||'◇'}
  private apply(r:TenantEntitlements){this.license=r;this.selectedPlan=r.plan;this.maxUsers=r.maxUsers;this.expiryDate=r.expiresAtUtc?.slice(0,10)||'';this.enabled=new Set(r.modules);this.busy=false}private resetDraft(){this.license=undefined;this.selectedPlan='demo';this.enabled=new Set();this.planChanged();this.busy=false}private ok(m:string){this.busy=false;this.success=true;this.message=m}private fail(m:string){this.busy=false;this.success=false;this.message=m}private error(e:any){return e?.error?.detail||e?.error?.title||'The operation could not be completed.'}
  private validPassword(value:string){return value.length>=10&&/[a-z]/.test(value)&&/[A-Z]/.test(value)&&/[0-9]/.test(value)&&/[^a-zA-Z0-9]/.test(value)}
}
