import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { PageHeader } from '../../shared/ui';
import { RealWorkspaceDraft, RealWorkspaceOptions, RealWorkspaceProspect, RealWorkspaceService } from './real-workspace.service';

@Component({
 standalone:true,
 imports:[CommonModule,FormsModule,RouterLink,PageHeader],
 template:`
 <qai-page-header title="Prepare Real Workspace" subtitle="Start from a template, edit tenant-owned prospects, save your work, then activate it."></qai-page-header>
 <div class="steps"><span [class.active]="step===1">1 Use case</span><span [class.active]="step===2">2 Template</span><span [class.active]="step===3">3 Prospects</span><span [class.active]="step===4">4 Activate</span></div>
 <p class="notice" *ngIf="draft">Saved workspace: <b>{{draft.name}}</b> · {{draft.status}} · updated {{draft.updatedAtUtc | date:'medium'}}</p>
 
 <section *ngIf="step===1" class="panel"><h2>What are you building?</h2><p>Choose the operating context first. The template is only a starting blueprint; your saved workspace becomes tenant-owned data.</p><div class="grid"><button class="choice" *ngFor="let item of options?.useCases" (click)="chooseUseCase(item.id)"><b>{{item.name}}</b><small>{{item.description}}</small></button></div></section>
 
 <section *ngIf="step===2" class="panel"><div class="heading"><div><h2>Choose a template</h2><p>Templates provide the initial configuration and starter prospects.</p></div><button class="secondary" (click)="step=1">Back</button></div><div class="grid"><button class="choice" *ngFor="let item of templates" [class.selected]="selectedTemplate===item.id" (click)="selectTemplate(item.id)"><b>{{item.name}}</b><small>{{item.description}}</small><div class="chips"><em *ngFor="let module of item.requiredModules">{{module}}</em><em>{{item.prospects.length}} starter prospects</em></div></button></div><div class="actions"><input [(ngModel)]="workspaceName" placeholder="Workspace name (optional)"/><button [disabled]="!selectedTemplate || saving" (click)="prepare()">{{saving?'Preparing…':'Create editable workspace'}}</button></div></section>
 
 <section *ngIf="step===3 && draft" class="panel"><div class="heading"><div><h2>Edit and select prospects</h2><p>Select one or more prospects. You can edit every field before activation.</p></div><span class="count">{{draft.selectedProspectIds.length}} selected</span></div><div class="prospects"><article *ngFor="let p of draft.prospects"><label class="select"><input type="checkbox" [checked]="isSelected(p.id)" (change)="toggle(p.id)"/> Include</label><div class="fields"><label>Company<input [(ngModel)]="p.companyName"/></label><label>Domain<input [(ngModel)]="p.domain"/></label><label>Contact<input [(ngModel)]="p.contactName"/></label><label>Email<input [(ngModel)]="p.email"/></label><label>Job title<input [(ngModel)]="p.jobTitle"/></label><label>Industry<input [(ngModel)]="p.industry"/></label><label>Country<input [(ngModel)]="p.country"/></label><label>Offer<input [(ngModel)]="p.offer"/></label><label class="wide">Pain hypothesis<textarea [(ngModel)]="p.painHypothesis"></textarea></label></div></article></div><div class="actions"><button class="secondary" (click)="step=2">Back</button><button [disabled]="saving" (click)="saveAndContinue()">{{saving?'Saving…':'Save & continue'}}</button></div></section>
 
 <section *ngIf="step===4 && draft" class="panel review"><h2>Review workspace</h2><p>This will create real tenant-owned prospect records from the selected, edited data. The template itself remains unchanged.</p><div class="summary"><div><b>{{draft.name}}</b><small>{{draft.useCaseId}} · {{draft.templateId}}</small></div><div><b>{{draft.selectedProspectIds.length}}</b><small>prospects selected</small></div></div><ul><li *ngFor="let p of selectedProspects"><b>{{p.companyName}}</b> — {{p.contactName}} · {{p.email}}</li></ul><div class="actions"><button class="secondary" (click)="step=3">Back & edit</button><button [disabled]="saving" (click)="activate()">{{saving?'Activating…':'Activate workspace'}}</button></div></section>
 
 <section *ngIf="draft?.status==='active'" class="success"><h2>Workspace activated</h2><p>Your selected prospects are now real tenant-owned workspace records.</p><a routerLink="/discover">Open acquisition</a><a routerLink="/golden-pipeline">Open Golden Pipeline</a></section>
 <p class="status" *ngIf="status" [class.error]="error">{{status}}</p>
 `,
 styles:[`.steps{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.steps span{padding:8px 12px;border:1px solid var(--border,#ddd);border-radius:999px;font-size:12px}.steps .active{font-weight:700;border-color:var(--primary,#2563eb)}.panel,.notice,.success{padding:24px;border:1px solid var(--border,#ddd);border-radius:14px;margin-bottom:18px}.panel h2{margin:0 0 8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin-top:18px}.choice{text-align:left;padding:18px;border:1px solid var(--border,#ddd);border-radius:12px;background:var(--surface,#fff);color:inherit;cursor:pointer}.choice b,.choice small{display:block}.choice small{margin-top:8px;opacity:.7}.choice.selected{outline:2px solid var(--primary,#2563eb)}.chips{display:flex;gap:6px;flex-wrap:wrap;margin-top:14px}.chips em{font-style:normal;font-size:11px;padding:4px 7px;border:1px solid var(--border,#ddd);border-radius:999px}.heading{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.actions{display:flex;gap:10px;justify-content:flex-end;align-items:center;margin-top:18px;flex-wrap:wrap}.actions input{flex:1;min-width:240px;padding:11px;border:1px solid var(--border,#ddd);border-radius:8px}.actions button,.success a{padding:11px 16px;border:0;border-radius:8px;background:var(--primary,#2563eb);color:#fff;font-weight:600;cursor:pointer;text-decoration:none}.actions button:disabled{opacity:.6}.secondary{background:transparent!important;color:inherit!important;border:1px solid var(--border,#ddd)!important}.count{font-size:12px;font-weight:700}.prospects{display:grid;gap:14px;margin-top:18px}.prospects article{padding:16px;border:1px solid var(--border,#ddd);border-radius:12px}.select{display:flex;gap:8px;align-items:center;font-weight:700}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.fields label{font-size:12px}.fields input,.fields textarea{display:block;width:100%;box-sizing:border-box;margin-top:5px;padding:9px;border:1px solid var(--border,#ddd);border-radius:7px;background:transparent;color:inherit}.fields textarea{min-height:70px;resize:vertical}.wide{grid-column:1/-1}.summary{display:flex;justify-content:space-between;gap:20px;padding:16px;border:1px solid var(--border,#ddd);border-radius:10px}.summary b,.summary small{display:block}.summary small{margin-top:5px;opacity:.7}.review ul{padding-left:20px}.success{border-width:2px}.success a{display:inline-block;margin-right:8px}.status{margin-top:12px}.error{color:#b91c1c}@media(max-width:650px){.fields{grid-template-columns:1fr}.wide{grid-column:auto}.heading{flex-direction:column}}`]
})
export class PrepareRealWorkspacePage {
 private readonly service=inject(RealWorkspaceService);
 options:RealWorkspaceOptions|null=null; draft:RealWorkspaceDraft|null=null; step=1; selectedUseCase=''; selectedTemplate=''; workspaceName=''; saving=false; status=''; error=false;
 ngOnInit():void { this.service.options().subscribe({next:x=>this.options=x,error:()=>this.fail('Could not load workspace templates.')}); this.service.current().subscribe({next:x=>{if(x){this.draft=x;this.selectedUseCase=x.useCaseId;this.selectedTemplate=x.templateId;this.workspaceName=x.name;this.step=x.status==='active'?4:3;}},error:()=>{}}); }
 get templates(){return (this.options?.templates||[]).filter(x=>!this.selectedUseCase||x.useCaseId===this.selectedUseCase);}
 get selectedProspects():RealWorkspaceProspect[]{return this.draft?.prospects.filter(x=>this.draft!.selectedProspectIds.includes(x.id))||[];}
 chooseUseCase(id:string):void {this.selectedUseCase=id;this.selectedTemplate='';this.step=2;}
 selectTemplate(id:string):void {this.selectedTemplate=id;}
 prepare():void {if(!this.selectedUseCase||!this.selectedTemplate)return;this.saving=true;this.clear();this.service.prepare(this.selectedUseCase,this.selectedTemplate,this.workspaceName).subscribe({next:x=>{this.draft=x;this.step=3;this.saving=false;this.status='Workspace draft created. Edit and select the prospects you want to activate.'},error:e=>{this.saving=false;this.fail(e?.error?.detail||'Could not create workspace draft.')}});}
 isSelected(id:string):boolean{return !!this.draft?.selectedProspectIds.includes(id);}
 toggle(id:string):void {if(!this.draft)return;this.draft={...this.draft,selectedProspectIds:this.isSelected(id)?this.draft.selectedProspectIds.filter(x=>x!==id):[...this.draft.selectedProspectIds,id]};}
 saveAndContinue():void {if(!this.draft)return;this.saving=true;this.clear();this.service.save(this.draft).subscribe({next:x=>{this.draft=x;this.step=4;this.saving=false;this.status='Workspace saved. Review the selected prospects and activate when ready.'},error:e=>{this.saving=false;this.fail(e?.error?.detail||'Could not save workspace.')}});}
 activate():void {if(!this.draft)return;this.saving=true;this.clear();this.service.activate(this.draft.workspaceId).subscribe({next:x=>{this.draft=x;this.saving=false;this.status='Workspace activated successfully.'},error:e=>{this.saving=false;this.fail(e?.error?.detail||'Could not activate workspace.')}});}
 private clear():void{this.status='';this.error=false;} private fail(message:string):void{this.status=message;this.error=true;}
}
