import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { PageHeader } from '../../shared/ui';
import { RealWorkspaceOptions, RealWorkspaceRequest, RealWorkspaceResult, RealWorkspaceService } from './real-workspace.service';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink,PageHeader],template:`
<qai-page-header title="Prepare Real Workspace" subtitle="Select the target market once. The platform automatically prepares and starts the acquisition operation."></qai-page-header>
<div class="steps"><span [class.active]="step===1">1 Area</span><span [class.active]="step===2">2 Target</span><span [class.active]="step===3">3 Automation</span></div>
<section *ngIf="step===1" class="panel"><h2>What should this workspace do?</h2><p>Select the operating area. This determines which automation is provisioned.</p><div class="grid"><button class="choice" *ngFor="let item of options?.useCases" [class.selected]="useCase===item.id" (click)="selectArea(item.id)"><b>{{item.name}}</b><small>{{item.description}}</small></button></div></section>
<section *ngIf="step===2" class="panel"><div class="heading"><div><h2>Define the target market</h2><p>You provide business context. Prospecting, enrichment, qualification and campaign setup happen automatically.</p></div><button class="secondary" (click)="step=1">Back</button></div><div class="form"><label>Template<select [(ngModel)]="templateKey"><option value="">Select template</option><option *ngFor="let t of templates" [value]="t.id">{{t.name}}</option></select></label><label>Industry<input [(ngModel)]="industry" placeholder="Logistics, SaaS, Manufacturing..."/></label><label>Region<input [(ngModel)]="region" placeholder="DACH, Europe, North America..."/></label><label>Countries<input [(ngModel)]="countries" placeholder="Germany, Austria, Switzerland"/></label><label>Workspace name<input [(ngModel)]="name" placeholder="Optional"/></label><label>Daily discovery limit<input type="number" [(ngModel)]="dailyDiscoveryLimit" min="1" max="100"/></label><label>Minimum qualification score<input type="number" [(ngModel)]="minimumScore" min="1" max="100"/></label></div><div class="automation"><b>Automation plan</b><div class="pipeline"><span>Configure Agent</span><i>→</i><span>Discover</span><i>→</i><span>Enrich</span><i>→</i><span>Qualify</span><i>→</i><span>Campaign</span></div></div><div class="actions"><button [disabled]="!ready||saving" (click)="start()">{{saving?'Preparing automation…':'Prepare & Start Automation'}}</button></div></section>
<section *ngIf="step===3" class="panel"><h2>Automation started</h2><p>Your real workspace is now operating as an automated acquisition system.</p><div class="timeline"><div class="done"><b>Workspace configured</b><small>Selected template and target market applied</small></div><div class="done"><b>Autonomous Agent active</b><small>{{result?.agentStatus}}</small></div><div [class.done]="!!result?.initialRunId"><b>Initial prospecting queued</b><small>Discovery runs automatically</small></div><div [class.done]="!!result?.targetListId"><b>Qualified target list ready</b><small>Qualified prospects enter automatically</small></div><div [class.done]="!!result?.campaignId"><b>Campaign running</b><small>Qualified prospects are enrolled automatically</small></div><div class="done"><b>Daily automation enabled</b><small>New qualified prospects continue flowing into the campaign</small></div></div><div class="actions"><a routerLink="/discover">Open Acquisition</a><a routerLink="/golden-pipeline" class="secondary-link">Open Golden Pipeline</a></div></section>
<p class="status" *ngIf="status" [class.error]="error">{{status}}</p>
`,styles:[`.steps{display:flex;gap:8px;margin-bottom:18px;flex-wrap:wrap}.steps span{padding:8px 12px;border:1px solid var(--border,#ddd);border-radius:999px;font-size:12px}.steps .active{font-weight:700;border-color:var(--primary,#2563eb)}.panel{padding:24px;border:1px solid var(--border,#ddd);border-radius:14px;margin-bottom:18px;background:var(--surface,#fff)}h2{margin:0 0 8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px;margin-top:18px}.choice{text-align:left;padding:20px;border:1px solid var(--border,#ddd);border-radius:12px;background:transparent;color:inherit;cursor:pointer}.choice b,.choice small{display:block}.choice small{margin-top:8px;opacity:.7}.choice.selected{outline:2px solid var(--primary,#2563eb)}.heading{display:flex;justify-content:space-between;gap:16px}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:20px}.form label{font-size:12px;font-weight:600}.form input,.form select{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:11px;border:1px solid var(--border,#ddd);border-radius:8px;background:transparent;color:inherit}.automation{margin-top:22px;padding:16px;border:1px solid var(--border,#ddd);border-radius:10px}.pipeline{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:12px}.pipeline span{padding:7px 10px;border:1px solid var(--border,#ddd);border-radius:999px;font-size:12px}.pipeline i{font-style:normal;opacity:.5}.actions{display:flex;gap:10px;justify-content:flex-end;margin-top:22px;flex-wrap:wrap}.actions button,.actions a{padding:11px 16px;border:0;border-radius:8px;background:var(--primary,#2563eb);color:#fff;font-weight:600;text-decoration:none;cursor:pointer}.secondary,.secondary-link{background:transparent!important;color:inherit!important;border:1px solid var(--border,#ddd)!important}.timeline{display:grid;margin-top:20px}.timeline div{position:relative;padding:16px 16px 16px 42px;border-left:2px solid var(--border,#ddd)}.timeline div:before{content:'○';position:absolute;left:-10px;top:13px;background:var(--surface,#fff);font-size:20px}.timeline .done:before{content:'✓';font-weight:800}.timeline b,.timeline small{display:block}.timeline small{margin-top:4px;opacity:.7}.status{margin-top:12px}.error{color:#b91c1c}@media(max-width:650px){.form{grid-template-columns:1fr}.heading{flex-direction:column}}`]
})
export class PrepareRealWorkspacePage {
 private readonly service=inject(RealWorkspaceService); options:RealWorkspaceOptions|null=null; result:RealWorkspaceResult|null=null; step=1; useCase=''; templateKey=''; industry=''; region=''; countries=''; name=''; dailyDiscoveryLimit=25; minimumScore=70; saving=false; status=''; error=false;
 ngOnInit(){this.service.options().subscribe({next:x=>this.options=x,error:()=>this.fail('Could not load workspace options.')});}
 get templates(){return (this.options?.templates||[]).filter(x=>!this.useCase||x.useCaseId===this.useCase);}
 get ready(){return !!this.useCase&&!!this.templateKey&&!!this.industry&&!!this.region;}
 selectArea(id:string){this.useCase=id;this.templateKey='';this.step=2;}
 start(){if(!this.ready)return;this.saving=true;this.status='';this.error=false;this.service.activate(this.request()).subscribe({next:x=>{this.result=x;this.step=3;this.saving=false;this.status='Workspace automation started successfully.'},error:e=>{this.saving=false;this.fail(e?.error?.detail||e?.error?.error||'Could not start workspace automation.')}});}
 private request():RealWorkspaceRequest{return {tenantId:this.tenantId(),name:this.name||null,useCase:this.useCase,templateKey:this.templateKey,industry:this.industry,region:this.region,countriesJson:JSON.stringify(this.countries.split(',').map(x=>x.trim()).filter(Boolean)),dailyDiscoveryLimit:this.dailyDiscoveryLimit,minimumScore:this.minimumScore};}
 private tenantId(){return localStorage.getItem('tenantId')||localStorage.getItem('qai_tenant_id')||'';} private fail(message:string){this.status=message;this.error=true;}
}
