import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { PageHeader } from '../../shared/ui';
import { PackageInstallResult, WorkspacePackage, WorkspacePackageId, WorkspacePackagesService } from './workspace-packages.service';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink,PageHeader],template:`
<qai-page-header title="Workspace Packages" subtitle="Install a reusable operating package into a tenant workspace."></qai-page-header>
<section class="package-metrics">
  <article><span class="metric-icon violet">▦</span><div><small>Available packages</small><strong>{{ packages.length }}</strong><em>Reusable workspace setups</em></div></article>
  <article><span class="metric-icon orange">✦</span><div><small>Recommended</small><strong>1</strong><em>FusionFleet Promotion</em></div></article>
  <article><span class="metric-icon green">✓</span><div><small>Provisioning</small><strong>Ready</strong><em>Install into workspace</em></div></article>
  <article><span class="metric-icon blue">⚙</span><div><small>Mode</small><strong>Tenant-safe</strong><em>Current or selected tenant</em></div></article>
</section>
<section class="intro"><div><b>PACKAGE LIBRARY</b><h2>Choose a complete operating package.</h2><p>Package installation provisions a complete scenario intentionally. For the editable tenant-owned flow, prepare a real workspace from a template first.</p><a routerLink="/platform/prepare-workspace" class="builder">Prepare Real Workspace →</a></div></section>
<section class="target"><label>Target tenant ID <input [(ngModel)]="tenantId" placeholder="Current tenant if empty" /></label><small>Leave empty for the current workspace. Master administrators can install into a specific tenant.</small></section>
<div class="grid"><article class="card" *ngFor="let item of packages" [class.selected]="selected===item.id"><header><b>{{item.name}}</b><span>{{item.id==='fusionfleet-promotion'?'RECOMMENDED':''}}</span></header><p>{{item.description}}</p><div class="modules"><small>Required modules</small><div><em *ngFor="let module of item.requiredModules">{{module}}</em><em *ngIf="!item.requiredModules.length">manual setup</em></div></div><button type="button" (click)="install(item)" [disabled]="installing">{{installing && selected===item.id?'Installing…':'Install package'}}</button></article></div>
<section *ngIf="result" class="result"><h3>{{result.scenario}}</h3><div><span>{{result.prospects}} prospects</span><span>{{result.campaigns}} campaigns</span><span>{{result.opportunities}} opportunities</span><span>{{result.meetings}} meetings</span><span>{{result.tickets}} tickets</span><span>{{result.automations}} automations</span></div><div class="next"><button type="button" (click)="continueWorkflow()">Continue to workflow</button><a *ngIf="result.packageId==='fusionfleet-promotion'" routerLink="/acquisition/autonomous">Configure FusionFleet automation</a><a *ngIf="result.packageId==='qualifyai-acquisition'" routerLink="/pipeline">Open revenue pipeline</a><a routerLink="/ai/agents">Open agents</a></div></section>
<p class="status" *ngIf="status" [class.error]="error">{{status}}</p>
` ,styles:[`.page-shell{min-height:100%}
:host{display:block;min-height:100%;background:#f5f7fb;color:#101828}
qai-page-header .page-header{margin:0 20px!important;padding:20px 0 16px!important;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important}
qai-page-header .page-header h1{color:#202124!important;font-size:22px!important;font-weight:700!important;letter-spacing:-.02em!important}
qai-page-header .page-header p{margin-top:5px!important;color:#667085!important;font-size:10px!important;line-height:1.5!important}
qai-page-header .page-header a,.page-header button{height:34px!important;min-height:34px!important;padding:0 12px!important;border:1px solid #dfe5ed!important;border-radius:8px!important;background:#fff!important;color:#475467!important;font-size:9px!important;font-weight:700!important;text-decoration:none!important}
qai-page-header .page-header a:hover,.page-header button:hover{border-color:#fdba74!important;background:#fffaf6!important;color:#c2410c!important}
qai-page-header .page-header a.primary{border-color:#f97316!important;background:#f97316!important;color:#fff!important}

.package-metrics{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px!important;margin:0 20px 14px!important}
.package-metrics article{position:relative!important;display:flex!important;gap:11px!important;min-height:92px!important;padding:15px 16px!important;border:1px solid #e3e8ef!important;border-radius:10px!important;background:#fff!important;box-shadow:0 2px 5px rgba(16,24,40,.035),0 7px 18px rgba(36,60,88,.05)!important}
.package-metrics article:before{content:""!important;position:absolute!important;left:0!important;top:0!important;width:100%!important;height:3px!important;border-radius:10px 10px 0 0!important;background:#7c3aed!important}
.package-metrics article:nth-child(2):before{background:#f97316!important}.package-metrics article:nth-child(3):before{background:#059669!important}.package-metrics article:nth-child(4):before{background:#2563eb!important}
.metric-icon{display:grid!important;width:32px!important;height:32px!important;flex:0 0 32px!important;place-items:center!important;border-radius:8px!important;background:#f2edff!important;color:#7c3aed!important;font-size:11px!important;font-weight:800!important}
.metric-icon.orange{background:#fff7ed!important;color:#f97316!important}.metric-icon.green{background:#eaf9f1!important;color:#059669!important}.metric-icon.blue{background:#edf4ff!important;color:#2563eb!important}
.package-metrics small,.package-metrics em{display:block!important;color:#667085!important;font-size:8px!important;line-height:1.35!important;font-style:normal!important}.package-metrics strong{display:block!important;margin:5px 0 2px!important;color:#172033!important;font-size:19px!important;line-height:1!important}.package-metrics em{color:#8293a7!important}

.intro,.target,.result{margin:0 20px 14px!important;border:1px solid #e3e8ef!important;border-radius:12px!important;background:#fff!important;box-shadow:0 2px 5px rgba(16,24,40,.035),0 7px 18px rgba(36,60,88,.05)!important}
.intro{padding:18px 20px!important}.intro b{color:#f97316!important;font-size:9px!important;letter-spacing:.11em!important}.intro h2{margin:5px 0 6px!important;color:#d95f0a!important;font-size:15px!important}.intro p{max-width:780px!important;margin:0!important;color:#667085!important;font-size:9px!important;line-height:1.6!important}.builder{display:inline-flex!important;align-items:center!important;margin-top:12px!important;height:32px!important;padding:0 10px!important;border:1px solid #fed7aa!important;border-radius:8px!important;background:#fff7ed!important;color:#c2410c!important;font-size:8px!important;font-weight:750!important;text-decoration:none!important}.builder:hover{background:#ffedd5!important}

.target{display:flex!important;align-items:flex-end!important;justify-content:space-between!important;gap:16px!important;padding:15px 16px!important}.target label{display:grid!important;gap:6px!important;color:#667085!important;font-size:9px!important;font-weight:700!important}.target input{width:min(420px,60vw)!important;height:36px!important;min-height:36px!important;padding:0 10px!important;border:1px solid #dfe5ed!important;border-radius:8px!important;background:#f8fafc!important;color:#172033!important;font-size:10px!important}.target input:focus{border-color:#f97316!important;outline:0!important;box-shadow:0 0 0 3px rgba(249,115,22,.08)!important}.target small{max-width:480px!important;color:#8293a7!important;font-size:8px!important;line-height:1.5!important}

.grid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:10px!important;margin:0 20px 18px!important}.card{position:relative!important;display:flex!important;flex-direction:column!important;min-width:0!important;min-height:228px!important;padding:16px!important;border:1px solid #e3e8ef!important;border-radius:12px!important;background:#fff!important;box-shadow:0 2px 5px rgba(16,24,40,.035),0 7px 18px rgba(36,60,88,.05)!important}.card:before{content:""!important;position:absolute!important;top:0!important;left:0!important;width:100%!important;height:3px!important;border-radius:12px 12px 0 0!important;background:#dfe5ed!important}.card.selected{border-color:#fdba74!important;background:#fffaf6!important;box-shadow:0 4px 12px rgba(249,115,22,.09)!important}.card.selected:before{background:#f97316!important}.card header{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:8px!important;padding-bottom:10px!important;border-bottom:1px solid #edf0f4!important}.card header b{color:#d95f0a!important;font-size:12px!important;font-weight:750!important}.card header span{padding:4px 7px!important;border:1px solid #ccebd9!important;border-radius:999px!important;background:#f0faf4!important;color:#15803d!important;font-size:7px!important;font-weight:800!important}.card>p{margin:11px 0 0!important;color:#667085!important;font-size:9px!important;line-height:1.6!important}.modules{margin:16px 0 15px!important}.modules>small{display:block!important;color:#98a2b3!important;font-size:8px!important;font-weight:700!important;text-transform:uppercase!important;letter-spacing:.06em!important}.modules div{display:flex!important;flex-wrap:wrap!important;gap:5px!important;margin-top:7px!important}.modules em{font-style:normal!important;padding:5px 7px!important;border:1px solid #e5e9f0!important;border-radius:7px!important;background:#f8fafc!important;color:#475467!important;font-size:8px!important}.card>button{margin-top:auto!important;width:100%!important;height:32px!important;min-height:32px!important;border:1px solid #fdba74!important;border-radius:8px!important;background:#fff7ed!important;color:#c2410c!important;font-size:9px!important;font-weight:750!important}.card>button:hover{background:#ffedd5!important}.card>button:disabled{opacity:.55!important;cursor:wait!important}

.result{padding:17px 18px!important}.result h3{margin:0!important;color:#d95f0a!important;font-size:13px!important}.result>div{display:flex!important;flex-wrap:wrap!important;gap:7px!important;margin-top:11px!important}.result span{padding:6px 8px!important;border:1px solid #e5e9f0!important;border-radius:999px!important;background:#f8fafc!important;color:#475467!important;font-size:8px!important;font-weight:700!important}.result .next{margin-top:13px!important;display:flex!important;align-items:center!important;gap:8px!important}.next button{width:auto!important;height:31px!important;padding:0 11px!important;border:0!important;border-radius:8px!important;background:#f97316!important;color:#fff!important;font-size:8px!important;font-weight:750!important}.next button:hover{background:#ea580c!important}.next a{height:31px!important;display:inline-flex!important;align-items:center!important;padding:0 10px!important;border:1px solid #dfe5ed!important;border-radius:8px!important;background:#fff!important;color:#475467!important;font-size:8px!important;font-weight:700!important;text-decoration:none!important}.next a:hover{border-color:#fdba74!important;background:#fffaf6!important;color:#c2410c!important}
.status{margin:0 20px 24px!important;padding:11px 13px!important;border-radius:9px!important;border:1px solid #ccebd9!important;background:#f0faf4!important;color:#15803d!important;font-size:9px!important}.status.error{border-color:#fecdd3!important;background:#fff1f2!important;color:#be123c!important}
@media(max-width:1000px){qai-page-header .page-header,.package-metrics,.intro,.target,.grid,.result,.status{margin-left:16px!important;margin-right:16px!important}.package-metrics{grid-template-columns:repeat(2,minmax(0,1fr))!important}.grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.target{align-items:flex-start!important;flex-direction:column!important}.target input{width:min(520px,100%)!important}}
@media(max-width:650px){qai-page-header .page-header,.package-metrics,.intro,.target,.grid,.result,.status{margin-left:12px!important;margin-right:12px!important}.package-metrics,.grid{grid-template-columns:1fr!important}.intro,.target,.result{padding:15px!important}.card{min-height:210px!important}.result .next{align-items:stretch!important;flex-direction:column!important}.next button,.next a{width:100%!important;justify-content:center!important}}`])
export class WorkspacePackagesPage {
 private readonly service=inject(WorkspacePackagesService); private readonly router=inject(Router); readonly packages=this.service.packages;
 tenantId=''; selected:WorkspacePackageId='fusionfleet-promotion'; installing=false; status=''; error=false; result:PackageInstallResult|null=null;
 install(item:WorkspacePackage):void { if(this.installing)return; this.selected=item.id; this.installing=true; this.error=false; this.result=null; this.status=`Installing ${item.name}…`; this.service.install({packageId:item.id,tenantId:this.tenantId.trim()||undefined}).subscribe({next:result=>{this.installing=false;this.result=result;this.status=`${item.name} installed successfully.`;},error:e=>{this.installing=false;this.error=true;this.status=e?.error?.detail||'Package installation failed.';}}); }
 continueWorkflow():void { if(!this.result)return; const route=this.result.packageId==='fusionfleet-promotion'?'/acquisition/autonomous':this.result.packageId==='qualifyai-acquisition'?'/pipeline':'/platform'; this.router.navigate([route]); }
}
